ltl order0_MUST_BE_TRUE { X( [](wp[0] -> <>(vcyl_extended && suction_on && carrying_wp && <>(wp_output && vcyl_extended && hcyl_retracted[0] && hcyl_retracted[1] && hcyl_retracted[2] && hcyl_retracted[3] && hcyl_retracted[4] && <>(vcyl_retracted && hcyl_retracted[0] && hcyl_retracted[1] && hcyl_retracted[2] && hcyl_retracted[3] && hcyl_retracted[4])))) ) }
ltl order1_MUST_BE_TRUE { X( [](wp[1] -> <>(vcyl_extended && suction_on && carrying_wp && <>(wp_output && vcyl_extended && hcyl_retracted[0] && hcyl_retracted[1] && hcyl_retracted[2] && hcyl_retracted[3] && hcyl_retracted[4] && <>(vcyl_retracted && hcyl_retracted[0] && hcyl_retracted[1] && hcyl_retracted[2] && hcyl_retracted[3] && hcyl_retracted[4])))) ) }
ltl order2_MUST_BE_TRUE { X( [](wp[2] -> <>(vcyl_extended && suction_on && carrying_wp && <>(wp_output && vcyl_extended && hcyl_retracted[0] && hcyl_retracted[1] && hcyl_retracted[2] && hcyl_retracted[3] && hcyl_retracted[4] && <>(vcyl_retracted && hcyl_retracted[0] && hcyl_retracted[1] && hcyl_retracted[2] && hcyl_retracted[3] && hcyl_retracted[4])))) ) }
ltl order3_MUST_BE_TRUE { X( [](wp[3] -> <>(vcyl_extended && suction_on && carrying_wp && <>(wp_output && vcyl_extended && hcyl_retracted[0] && hcyl_retracted[1] && hcyl_retracted[2] && hcyl_retracted[3] && hcyl_retracted[4] && <>(vcyl_retracted && hcyl_retracted[0] && hcyl_retracted[1] && hcyl_retracted[2] && hcyl_retracted[3] && hcyl_retracted[4])))) ) }
ltl order4_MUST_BE_TRUE { X( [](wp[4] -> <>(vcyl_extended && suction_on && carrying_wp && <>(wp_output && vcyl_extended && hcyl_retracted[0] && hcyl_retracted[1] && hcyl_retracted[2] && hcyl_retracted[3] && hcyl_retracted[4] && <>(vcyl_retracted && hcyl_retracted[0] && hcyl_retracted[1] && hcyl_retracted[2] && hcyl_retracted[3] && hcyl_retracted[4])))) ) }
ltl order5_MUST_BE_TRUE { X( [](wp[5] -> <>(vcyl_extended && suction_on && carrying_wp && <>(wp_output && vcyl_extended && hcyl_retracted[0] && hcyl_retracted[1] && hcyl_retracted[2] && hcyl_retracted[3] && hcyl_retracted[4] && <>(vcyl_retracted && hcyl_retracted[0] && hcyl_retracted[1] && hcyl_retracted[2] && hcyl_retracted[3] && hcyl_retracted[4])))) ) }
ltl order6_MUST_BE_TRUE { X( [](wp[6] -> <>(vcyl_extended && suction_on && carrying_wp && <>(wp_output && vcyl_extended && hcyl_retracted[0] && hcyl_retracted[1] && hcyl_retracted[2] && hcyl_retracted[3] && hcyl_retracted[4] && <>(vcyl_retracted && hcyl_retracted[0] && hcyl_retracted[1] && hcyl_retracted[2] && hcyl_retracted[3] && hcyl_retracted[4])))) ) }
ltl order7_MUST_BE_TRUE { X( [](wp[7] -> <>(vcyl_extended && suction_on && carrying_wp && <>(wp_output && vcyl_extended && hcyl_retracted[0] && hcyl_retracted[1] && hcyl_retracted[2] && hcyl_retracted[3] && hcyl_retracted[4] && <>(vcyl_retracted && hcyl_retracted[0] && hcyl_retracted[1] && hcyl_retracted[2] && hcyl_retracted[3] && hcyl_retracted[4])))) ) }
ltl order8_MUST_BE_TRUE { X( [](wp[8] -> <>(vcyl_extended && suction_on && carrying_wp && <>(wp_output && vcyl_extended && hcyl_retracted[0] && hcyl_retracted[1] && hcyl_retracted[2] && hcyl_retracted[3] && hcyl_retracted[4] && <>(vcyl_retracted && hcyl_retracted[0] && hcyl_retracted[1] && hcyl_retracted[2] && hcyl_retracted[3] && hcyl_retracted[4])))) ) }
ltl order9_MUST_BE_TRUE { X( [](wp[9] -> <>(vcyl_extended && suction_on && carrying_wp && <>(wp_output && vcyl_extended && hcyl_retracted[0] && hcyl_retracted[1] && hcyl_retracted[2] && hcyl_retracted[3] && hcyl_retracted[4] && <>(vcyl_retracted && hcyl_retracted[0] && hcyl_retracted[1] && hcyl_retracted[2] && hcyl_retracted[3] && hcyl_retracted[4])))) ) }
ltl order10_MUST_BE_TRUE { X( [](wp[10] -> <>(vcyl_extended && suction_on && carrying_wp && <>(wp_output && vcyl_extended && hcyl_retracted[0] && hcyl_retracted[1] && hcyl_retracted[2] && hcyl_retracted[3] && hcyl_retracted[4] && <>(vcyl_retracted && hcyl_retracted[0] && hcyl_retracted[1] && hcyl_retracted[2] && hcyl_retracted[3] && hcyl_retracted[4])))) ) }
ltl order11_MUST_BE_TRUE { X( [](wp[11] -> <>(vcyl_extended && suction_on && carrying_wp && <>(wp_output && vcyl_extended && hcyl_retracted[0] && hcyl_retracted[1] && hcyl_retracted[2] && hcyl_retracted[3] && hcyl_retracted[4] && <>(vcyl_retracted && hcyl_retracted[0] && hcyl_retracted[1] && hcyl_retracted[2] && hcyl_retracted[3] && hcyl_retracted[4])))) ) }
ltl order12_MUST_BE_TRUE { X( [](wp[12] -> <>(vcyl_extended && suction_on && carrying_wp && <>(wp_output && vcyl_extended && hcyl_retracted[0] && hcyl_retracted[1] && hcyl_retracted[2] && hcyl_retracted[3] && hcyl_retracted[4] && <>(vcyl_retracted && hcyl_retracted[0] && hcyl_retracted[1] && hcyl_retracted[2] && hcyl_retracted[3] && hcyl_retracted[4])))) ) }
ltl order13_MUST_BE_TRUE { X( [](wp[13] -> <>(vcyl_extended && suction_on && carrying_wp && <>(wp_output && vcyl_extended && hcyl_retracted[0] && hcyl_retracted[1] && hcyl_retracted[2] && hcyl_retracted[3] && hcyl_retracted[4] && <>(vcyl_retracted && hcyl_retracted[0] && hcyl_retracted[1] && hcyl_retracted[2] && hcyl_retracted[3] && hcyl_retracted[4])))) ) }
ltl order14_MUST_BE_TRUE { X( [](wp[14] -> <>(vcyl_extended && suction_on && carrying_wp && <>(wp_output && vcyl_extended && hcyl_retracted[0] && hcyl_retracted[1] && hcyl_retracted[2] && hcyl_retracted[3] && hcyl_retracted[4] && <>(vcyl_retracted && hcyl_retracted[0] && hcyl_retracted[1] && hcyl_retracted[2] && hcyl_retracted[3] && hcyl_retracted[4])))) ) }
ltl order15_MUST_BE_TRUE { X( [](wp[15] -> <>(vcyl_extended && suction_on && carrying_wp && <>(wp_output && vcyl_extended && hcyl_retracted[0] && hcyl_retracted[1] && hcyl_retracted[2] && hcyl_retracted[3] && hcyl_retracted[4] && <>(vcyl_retracted && hcyl_retracted[0] && hcyl_retracted[1] && hcyl_retracted[2] && hcyl_retracted[3] && hcyl_retracted[4])))) ) }
ltl order16_MUST_BE_TRUE { X( [](wp[16] -> <>(vcyl_extended && suction_on && carrying_wp && <>(wp_output && vcyl_extended && hcyl_retracted[0] && hcyl_retracted[1] && hcyl_retracted[2] && hcyl_retracted[3] && hcyl_retracted[4] && <>(vcyl_retracted && hcyl_retracted[0] && hcyl_retracted[1] && hcyl_retracted[2] && hcyl_retracted[3] && hcyl_retracted[4])))) ) }
ltl order17_MUST_BE_TRUE { X( [](wp[17] -> <>(vcyl_extended && suction_on && carrying_wp && <>(wp_output && vcyl_extended && hcyl_retracted[0] && hcyl_retracted[1] && hcyl_retracted[2] && hcyl_retracted[3] && hcyl_retracted[4] && <>(vcyl_retracted && hcyl_retracted[0] && hcyl_retracted[1] && hcyl_retracted[2] && hcyl_retracted[3] && hcyl_retracted[4])))) ) }
ltl order18_MUST_BE_TRUE { X( [](wp[18] -> <>(vcyl_extended && suction_on && carrying_wp && <>(wp_output && vcyl_extended && hcyl_retracted[0] && hcyl_retracted[1] && hcyl_retracted[2] && hcyl_retracted[3] && hcyl_retracted[4] && <>(vcyl_retracted && hcyl_retracted[0] && hcyl_retracted[1] && hcyl_retracted[2] && hcyl_retracted[3] && hcyl_retracted[4])))) ) }
ltl order19_MUST_BE_TRUE { X( [](wp[19] -> <>(vcyl_extended && suction_on && carrying_wp && <>(wp_output && vcyl_extended && hcyl_retracted[0] && hcyl_retracted[1] && hcyl_retracted[2] && hcyl_retracted[3] && hcyl_retracted[4] && <>(vcyl_retracted && hcyl_retracted[0] && hcyl_retracted[1] && hcyl_retracted[2] && hcyl_retracted[3] && hcyl_retracted[4])))) ) }
ltl order20_MUST_BE_TRUE { X( [](wp[20] -> <>(vcyl_extended && suction_on && carrying_wp && <>(wp_output && vcyl_extended && hcyl_retracted[0] && hcyl_retracted[1] && hcyl_retracted[2] && hcyl_retracted[3] && hcyl_retracted[4] && <>(vcyl_retracted && hcyl_retracted[0] && hcyl_retracted[1] && hcyl_retracted[2] && hcyl_retracted[3] && hcyl_retracted[4])))) ) }
ltl order21_MUST_BE_TRUE { X( [](wp[21] -> <>(vcyl_extended && suction_on && carrying_wp && <>(wp_output && vcyl_extended && hcyl_retracted[0] && hcyl_retracted[1] && hcyl_retracted[2] && hcyl_retracted[3] && hcyl_retracted[4] && <>(vcyl_retracted && hcyl_retracted[0] && hcyl_retracted[1] && hcyl_retracted[2] && hcyl_retracted[3] && hcyl_retracted[4])))) ) }
ltl order22_MUST_BE_TRUE { X( [](wp[22] -> <>(vcyl_extended && suction_on && carrying_wp && <>(wp_output && vcyl_extended && hcyl_retracted[0] && hcyl_retracted[1] && hcyl_retracted[2] && hcyl_retracted[3] && hcyl_retracted[4] && <>(vcyl_retracted && hcyl_retracted[0] && hcyl_retracted[1] && hcyl_retracted[2] && hcyl_retracted[3] && hcyl_retracted[4])))) ) }
ltl order23_MUST_BE_TRUE { X( [](wp[23] -> <>(vcyl_extended && suction_on && carrying_wp && <>(wp_output && vcyl_extended && hcyl_retracted[0] && hcyl_retracted[1] && hcyl_retracted[2] && hcyl_retracted[3] && hcyl_retracted[4] && <>(vcyl_retracted && hcyl_retracted[0] && hcyl_retracted[1] && hcyl_retracted[2] && hcyl_retracted[3] && hcyl_retracted[4])))) ) }
ltl order24_MUST_BE_TRUE { X( [](wp[24] -> <>(vcyl_extended && suction_on && carrying_wp && <>(wp_output && vcyl_extended && hcyl_retracted[0] && hcyl_retracted[1] && hcyl_retracted[2] && hcyl_retracted[3] && hcyl_retracted[4] && <>(vcyl_retracted && hcyl_retracted[0] && hcyl_retracted[1] && hcyl_retracted[2] && hcyl_retracted[3] && hcyl_retracted[4])))) ) }
ltl order25_MUST_BE_TRUE { X( [](wp[25] -> <>(vcyl_extended && suction_on && carrying_wp && <>(wp_output && vcyl_extended && hcyl_retracted[0] && hcyl_retracted[1] && hcyl_retracted[2] && hcyl_retracted[3] && hcyl_retracted[4] && <>(vcyl_retracted && hcyl_retracted[0] && hcyl_retracted[1] && hcyl_retracted[2] && hcyl_retracted[3] && hcyl_retracted[4])))) ) }
ltl order26_MUST_BE_TRUE { X( [](wp[26] -> <>(vcyl_extended && suction_on && carrying_wp && <>(wp_output && vcyl_extended && hcyl_retracted[0] && hcyl_retracted[1] && hcyl_retracted[2] && hcyl_retracted[3] && hcyl_retracted[4] && <>(vcyl_retracted && hcyl_retracted[0] && hcyl_retracted[1] && hcyl_retracted[2] && hcyl_retracted[3] && hcyl_retracted[4])))) ) }
ltl order27_MUST_BE_TRUE { X( [](wp[27] -> <>(vcyl_extended && suction_on && carrying_wp && <>(wp_output && vcyl_extended && hcyl_retracted[0] && hcyl_retracted[1] && hcyl_retracted[2] && hcyl_retracted[3] && hcyl_retracted[4] && <>(vcyl_retracted && hcyl_retracted[0] && hcyl_retracted[1] && hcyl_retracted[2] && hcyl_retracted[3] && hcyl_retracted[4])))) ) }
ltl order28_MUST_BE_TRUE { X( [](wp[28] -> <>(vcyl_extended && suction_on && carrying_wp && <>(wp_output && vcyl_extended && hcyl_retracted[0] && hcyl_retracted[1] && hcyl_retracted[2] && hcyl_retracted[3] && hcyl_retracted[4] && <>(vcyl_retracted && hcyl_retracted[0] && hcyl_retracted[1] && hcyl_retracted[2] && hcyl_retracted[3] && hcyl_retracted[4])))) ) }
ltl order29_MUST_BE_TRUE { X( [](wp[29] -> <>(vcyl_extended && suction_on && carrying_wp && <>(wp_output && vcyl_extended && hcyl_retracted[0] && hcyl_retracted[1] && hcyl_retracted[2] && hcyl_retracted[3] && hcyl_retracted[4] && <>(vcyl_retracted && hcyl_retracted[0] && hcyl_retracted[1] && hcyl_retracted[2] && hcyl_retracted[3] && hcyl_retracted[4])))) ) }
ltl order30_MUST_BE_TRUE { X( [](wp[30] -> <>(vcyl_extended && suction_on && carrying_wp && <>(wp_output && vcyl_extended && hcyl_retracted[0] && hcyl_retracted[1] && hcyl_retracted[2] && hcyl_retracted[3] && hcyl_retracted[4] && <>(vcyl_retracted && hcyl_retracted[0] && hcyl_retracted[1] && hcyl_retracted[2] && hcyl_retracted[3] && hcyl_retracted[4])))) ) }

ltl disappear0_MUST_BE_TRUE { X( []((wp[0] && !adding_wp[0]) -> <>(!wp[0] || adding_wp[0])) ) }
ltl disappear1_MUST_BE_TRUE { X( []((wp[1] && !adding_wp[1]) -> <>(!wp[1] || adding_wp[0] || adding_wp[1])) ) }
ltl disappear2_MUST_BE_TRUE { X( []((wp[2] && !adding_wp[2]) -> <>(!wp[2] || adding_wp[0] || adding_wp[1] || adding_wp[2])) ) }
ltl disappear3_MUST_BE_TRUE { X( []((wp[3] && !adding_wp[3]) -> <>(!wp[3] || adding_wp[0] || adding_wp[1] || adding_wp[2] || adding_wp[3])) ) }
ltl disappear4_MUST_BE_TRUE { X( []((wp[4] && !adding_wp[4]) -> <>(!wp[4] || adding_wp[0] || adding_wp[1] || adding_wp[2] || adding_wp[3] || adding_wp[4])) ) }
ltl disappear5_MUST_BE_TRUE { X( []((wp[5] && !adding_wp[5]) -> <>(!wp[5] || adding_wp[0] || adding_wp[1] || adding_wp[2] || adding_wp[3] || adding_wp[4] || adding_wp[5])) ) }
ltl disappear6_MUST_BE_TRUE { X( []((wp[6] && !adding_wp[6]) -> <>(!wp[6] || adding_wp[0] || adding_wp[1] || adding_wp[2] || adding_wp[3] || adding_wp[4] || adding_wp[5] || adding_wp[6])) ) }
ltl disappear7_MUST_BE_TRUE { X( []((wp[7] && !adding_wp[7]) -> <>(!wp[7] || adding_wp[0] || adding_wp[1] || adding_wp[2] || adding_wp[3] || adding_wp[4] || adding_wp[5] || adding_wp[6] || adding_wp[7])) ) }
ltl disappear8_MUST_BE_TRUE { X( []((wp[8] && !adding_wp[8]) -> <>(!wp[8] || adding_wp[0] || adding_wp[1] || adding_wp[2] || adding_wp[3] || adding_wp[4] || adding_wp[5] || adding_wp[6] || adding_wp[7] || adding_wp[8])) ) }
ltl disappear9_MUST_BE_TRUE { X( []((wp[9] && !adding_wp[9]) -> <>(!wp[9] || adding_wp[0] || adding_wp[1] || adding_wp[2] || adding_wp[3] || adding_wp[4] || adding_wp[5] || adding_wp[6] || adding_wp[7] || adding_wp[8] || adding_wp[9])) ) }
ltl disappear10_MUST_BE_TRUE { X( []((wp[10] && !adding_wp[10]) -> <>(!wp[10] || adding_wp[0] || adding_wp[1] || adding_wp[2] || adding_wp[3] || adding_wp[4] || adding_wp[5] || adding_wp[6] || adding_wp[7] || adding_wp[8] || adding_wp[9] || adding_wp[10])) ) }
ltl disappear11_MUST_BE_TRUE { X( []((wp[11] && !adding_wp[11]) -> <>(!wp[11] || adding_wp[0] || adding_wp[1] || adding_wp[2] || adding_wp[3] || adding_wp[4] || adding_wp[5] || adding_wp[6] || adding_wp[7] || adding_wp[8] || adding_wp[9] || adding_wp[10] || adding_wp[11])) ) }
ltl disappear12_MUST_BE_TRUE { X( []((wp[12] && !adding_wp[12]) -> <>(!wp[12] || adding_wp[0] || adding_wp[1] || adding_wp[2] || adding_wp[3] || adding_wp[4] || adding_wp[5] || adding_wp[6] || adding_wp[7] || adding_wp[8] || adding_wp[9] || adding_wp[10] || adding_wp[11] || adding_wp[12])) ) }
ltl disappear13_MUST_BE_TRUE { X( []((wp[13] && !adding_wp[13]) -> <>(!wp[13] || adding_wp[0] || adding_wp[1] || adding_wp[2] || adding_wp[3] || adding_wp[4] || adding_wp[5] || adding_wp[6] || adding_wp[7] || adding_wp[8] || adding_wp[9] || adding_wp[10] || adding_wp[11] || adding_wp[12] || adding_wp[13])) ) }
ltl disappear14_MUST_BE_TRUE { X( []((wp[14] && !adding_wp[14]) -> <>(!wp[14] || adding_wp[0] || adding_wp[1] || adding_wp[2] || adding_wp[3] || adding_wp[4] || adding_wp[5] || adding_wp[6] || adding_wp[7] || adding_wp[8] || adding_wp[9] || adding_wp[10] || adding_wp[11] || adding_wp[12] || adding_wp[13] || adding_wp[14])) ) }
ltl disappear15_MUST_BE_TRUE { X( []((wp[15] && !adding_wp[15]) -> <>(!wp[15] || adding_wp[0] || adding_wp[1] || adding_wp[2] || adding_wp[3] || adding_wp[4] || adding_wp[5] || adding_wp[6] || adding_wp[7] || adding_wp[8] || adding_wp[9] || adding_wp[10] || adding_wp[11] || adding_wp[12] || adding_wp[13] || adding_wp[14] || adding_wp[15])) ) }
ltl disappear16_MUST_BE_TRUE { X( []((wp[16] && !adding_wp[16]) -> <>(!wp[16] || adding_wp[0] || adding_wp[1] || adding_wp[2] || adding_wp[3] || adding_wp[4] || adding_wp[5] || adding_wp[6] || adding_wp[7] || adding_wp[8] || adding_wp[9] || adding_wp[10] || adding_wp[11] || adding_wp[12] || adding_wp[13] || adding_wp[14] || adding_wp[15] || adding_wp[16])) ) }
ltl disappear17_MUST_BE_TRUE { X( []((wp[17] && !adding_wp[17]) -> <>(!wp[17] || adding_wp[0] || adding_wp[1] || adding_wp[2] || adding_wp[3] || adding_wp[4] || adding_wp[5] || adding_wp[6] || adding_wp[7] || adding_wp[8] || adding_wp[9] || adding_wp[10] || adding_wp[11] || adding_wp[12] || adding_wp[13] || adding_wp[14] || adding_wp[15] || adding_wp[16] || adding_wp[17])) ) }
ltl disappear18_MUST_BE_TRUE { X( []((wp[18] && !adding_wp[18]) -> <>(!wp[18] || adding_wp[0] || adding_wp[1] || adding_wp[2] || adding_wp[3] || adding_wp[4] || adding_wp[5] || adding_wp[6] || adding_wp[7] || adding_wp[8] || adding_wp[9] || adding_wp[10] || adding_wp[11] || adding_wp[12] || adding_wp[13] || adding_wp[14] || adding_wp[15] || adding_wp[16] || adding_wp[17] || adding_wp[18])) ) }
ltl disappear19_MUST_BE_TRUE { X( []((wp[19] && !adding_wp[19]) -> <>(!wp[19] || adding_wp[0] || adding_wp[1] || adding_wp[2] || adding_wp[3] || adding_wp[4] || adding_wp[5] || adding_wp[6] || adding_wp[7] || adding_wp[8] || adding_wp[9] || adding_wp[10] || adding_wp[11] || adding_wp[12] || adding_wp[13] || adding_wp[14] || adding_wp[15] || adding_wp[16] || adding_wp[17] || adding_wp[18] || adding_wp[19])) ) }
ltl disappear20_MUST_BE_TRUE { X( []((wp[20] && !adding_wp[20]) -> <>(!wp[20] || adding_wp[0] || adding_wp[1] || adding_wp[2] || adding_wp[3] || adding_wp[4] || adding_wp[5] || adding_wp[6] || adding_wp[7] || adding_wp[8] || adding_wp[9] || adding_wp[10] || adding_wp[11] || adding_wp[12] || adding_wp[13] || adding_wp[14] || adding_wp[15] || adding_wp[16] || adding_wp[17] || adding_wp[18] || adding_wp[19] || adding_wp[20])) ) }
ltl disappear21_MUST_BE_TRUE { X( []((wp[21] && !adding_wp[21]) -> <>(!wp[21] || adding_wp[0] || adding_wp[1] || adding_wp[2] || adding_wp[3] || adding_wp[4] || adding_wp[5] || adding_wp[6] || adding_wp[7] || adding_wp[8] || adding_wp[9] || adding_wp[10] || adding_wp[11] || adding_wp[12] || adding_wp[13] || adding_wp[14] || adding_wp[15] || adding_wp[16] || adding_wp[17] || adding_wp[18] || adding_wp[19] || adding_wp[20] || adding_wp[21])) ) }
ltl disappear22_MUST_BE_TRUE { X( []((wp[22] && !adding_wp[22]) -> <>(!wp[22] || adding_wp[0] || adding_wp[1] || adding_wp[2] || adding_wp[3] || adding_wp[4] || adding_wp[5] || adding_wp[6] || adding_wp[7] || adding_wp[8] || adding_wp[9] || adding_wp[10] || adding_wp[11] || adding_wp[12] || adding_wp[13] || adding_wp[14] || adding_wp[15] || adding_wp[16] || adding_wp[17] || adding_wp[18] || adding_wp[19] || adding_wp[20] || adding_wp[21] || adding_wp[22])) ) }
ltl disappear23_MUST_BE_TRUE { X( []((wp[23] && !adding_wp[23]) -> <>(!wp[23] || adding_wp[0] || adding_wp[1] || adding_wp[2] || adding_wp[3] || adding_wp[4] || adding_wp[5] || adding_wp[6] || adding_wp[7] || adding_wp[8] || adding_wp[9] || adding_wp[10] || adding_wp[11] || adding_wp[12] || adding_wp[13] || adding_wp[14] || adding_wp[15] || adding_wp[16] || adding_wp[17] || adding_wp[18] || adding_wp[19] || adding_wp[20] || adding_wp[21] || adding_wp[22] || adding_wp[23])) ) }
ltl disappear24_MUST_BE_TRUE { X( []((wp[24] && !adding_wp[24]) -> <>(!wp[24] || adding_wp[0] || adding_wp[1] || adding_wp[2] || adding_wp[3] || adding_wp[4] || adding_wp[5] || adding_wp[6] || adding_wp[7] || adding_wp[8] || adding_wp[9] || adding_wp[10] || adding_wp[11] || adding_wp[12] || adding_wp[13] || adding_wp[14] || adding_wp[15] || adding_wp[16] || adding_wp[17] || adding_wp[18] || adding_wp[19] || adding_wp[20] || adding_wp[21] || adding_wp[22] || adding_wp[23] || adding_wp[24])) ) }
ltl disappear25_MUST_BE_TRUE { X( []((wp[25] && !adding_wp[25]) -> <>(!wp[25] || adding_wp[0] || adding_wp[1] || adding_wp[2] || adding_wp[3] || adding_wp[4] || adding_wp[5] || adding_wp[6] || adding_wp[7] || adding_wp[8] || adding_wp[9] || adding_wp[10] || adding_wp[11] || adding_wp[12] || adding_wp[13] || adding_wp[14] || adding_wp[15] || adding_wp[16] || adding_wp[17] || adding_wp[18] || adding_wp[19] || adding_wp[20] || adding_wp[21] || adding_wp[22] || adding_wp[23] || adding_wp[24] || adding_wp[25])) ) }
ltl disappear26_MUST_BE_TRUE { X( []((wp[26] && !adding_wp[26]) -> <>(!wp[26] || adding_wp[0] || adding_wp[1] || adding_wp[2] || adding_wp[3] || adding_wp[4] || adding_wp[5] || adding_wp[6] || adding_wp[7] || adding_wp[8] || adding_wp[9] || adding_wp[10] || adding_wp[11] || adding_wp[12] || adding_wp[13] || adding_wp[14] || adding_wp[15] || adding_wp[16] || adding_wp[17] || adding_wp[18] || adding_wp[19] || adding_wp[20] || adding_wp[21] || adding_wp[22] || adding_wp[23] || adding_wp[24] || adding_wp[25] || adding_wp[26])) ) }
ltl disappear27_MUST_BE_TRUE { X( []((wp[27] && !adding_wp[27]) -> <>(!wp[27] || adding_wp[0] || adding_wp[1] || adding_wp[2] || adding_wp[3] || adding_wp[4] || adding_wp[5] || adding_wp[6] || adding_wp[7] || adding_wp[8] || adding_wp[9] || adding_wp[10] || adding_wp[11] || adding_wp[12] || adding_wp[13] || adding_wp[14] || adding_wp[15] || adding_wp[16] || adding_wp[17] || adding_wp[18] || adding_wp[19] || adding_wp[20] || adding_wp[21] || adding_wp[22] || adding_wp[23] || adding_wp[24] || adding_wp[25] || adding_wp[26] || adding_wp[27])) ) }
ltl disappear28_MUST_BE_TRUE { X( []((wp[28] && !adding_wp[28]) -> <>(!wp[28] || adding_wp[0] || adding_wp[1] || adding_wp[2] || adding_wp[3] || adding_wp[4] || adding_wp[5] || adding_wp[6] || adding_wp[7] || adding_wp[8] || adding_wp[9] || adding_wp[10] || adding_wp[11] || adding_wp[12] || adding_wp[13] || adding_wp[14] || adding_wp[15] || adding_wp[16] || adding_wp[17] || adding_wp[18] || adding_wp[19] || adding_wp[20] || adding_wp[21] || adding_wp[22] || adding_wp[23] || adding_wp[24] || adding_wp[25] || adding_wp[26] || adding_wp[27] || adding_wp[28])) ) }
ltl disappear29_MUST_BE_TRUE { X( []((wp[29] && !adding_wp[29]) -> <>(!wp[29] || adding_wp[0] || adding_wp[1] || adding_wp[2] || adding_wp[3] || adding_wp[4] || adding_wp[5] || adding_wp[6] || adding_wp[7] || adding_wp[8] || adding_wp[9] || adding_wp[10] || adding_wp[11] || adding_wp[12] || adding_wp[13] || adding_wp[14] || adding_wp[15] || adding_wp[16] || adding_wp[17] || adding_wp[18] || adding_wp[19] || adding_wp[20] || adding_wp[21] || adding_wp[22] || adding_wp[23] || adding_wp[24] || adding_wp[25] || adding_wp[26] || adding_wp[27] || adding_wp[28] || adding_wp[29])) ) }
ltl disappear30_MUST_BE_TRUE { X( []((wp[30] && !adding_wp[30]) -> <>(!wp[30] || adding_wp[0] || adding_wp[1] || adding_wp[2] || adding_wp[3] || adding_wp[4] || adding_wp[5] || adding_wp[6] || adding_wp[7] || adding_wp[8] || adding_wp[9] || adding_wp[10] || adding_wp[11] || adding_wp[12] || adding_wp[13] || adding_wp[14] || adding_wp[15] || adding_wp[16] || adding_wp[17] || adding_wp[18] || adding_wp[19] || adding_wp[20] || adding_wp[21] || adding_wp[22] || adding_wp[23] || adding_wp[24] || adding_wp[25] || adding_wp[26] || adding_wp[27] || adding_wp[28] || adding_wp[29] || adding_wp[30])) ) }

ltl additional0_MUST_BE_TRUE { X( [](carrying_wp -> <>(wp_output && !suction_on)) ) }
ltl additional1_MUST_BE_TRUE { X( [](suction_on -> (carrying_wp || wp[0] || wp[1] || wp[2] || wp[3] || wp[4] || wp[5] || wp[6] || wp[7] || wp[8] || wp[9] || wp[10] || wp[11] || wp[12] || wp[13] || wp[14] || wp[15] || wp[16] || wp[17] || wp[18] || wp[19] || wp[20] || wp[21] || wp[22] || wp[23] || wp[24] || wp[25] || wp[26] || wp[27] || wp[28] || wp[29] || wp[30])) ) }
ltl additional2_MUST_BE_TRUE { X( [](suction_on -> <> !suction_on) ) }

ltl order0_MUST_BE_FALSE { X( [](wp[0] -> <>(vcyl_extended && suction_on && carrying_wp && <>(wp_output && vcyl_extended && hcyl_retracted[0] && hcyl_retracted[1] && hcyl_retracted[2] && hcyl_retracted[3] && hcyl_retracted[4] && <>(vcyl_retracted && (hcyl_extended[0] || hcyl_extended[1] || hcyl_extended[2] || hcyl_extended[3] || hcyl_extended[4]))))) ) }
ltl order1_MUST_BE_FALSE { X( [](wp[1] -> <>(vcyl_extended && suction_on && carrying_wp && <>(wp_output && vcyl_extended && hcyl_retracted[0] && hcyl_retracted[1] && hcyl_retracted[2] && hcyl_retracted[3] && hcyl_retracted[4] && <>(vcyl_retracted && (hcyl_extended[0] || hcyl_extended[1] || hcyl_extended[2] || hcyl_extended[3] || hcyl_extended[4]))))) ) }
ltl order2_MUST_BE_FALSE { X( [](wp[2] -> <>(vcyl_extended && suction_on && carrying_wp && <>(wp_output && vcyl_extended && hcyl_retracted[0] && hcyl_retracted[1] && hcyl_retracted[2] && hcyl_retracted[3] && hcyl_retracted[4] && <>(vcyl_retracted && (hcyl_extended[0] || hcyl_extended[1] || hcyl_extended[2] || hcyl_extended[3] || hcyl_extended[4]))))) ) }
ltl order3_MUST_BE_FALSE { X( [](wp[3] -> <>(vcyl_extended && suction_on && carrying_wp && <>(wp_output && vcyl_extended && hcyl_retracted[0] && hcyl_retracted[1] && hcyl_retracted[2] && hcyl_retracted[3] && hcyl_retracted[4] && <>(vcyl_retracted && (hcyl_extended[0] || hcyl_extended[1] || hcyl_extended[2] || hcyl_extended[3] || hcyl_extended[4]))))) ) }
ltl order4_MUST_BE_FALSE { X( [](wp[4] -> <>(vcyl_extended && suction_on && carrying_wp && <>(wp_output && vcyl_extended && hcyl_retracted[0] && hcyl_retracted[1] && hcyl_retracted[2] && hcyl_retracted[3] && hcyl_retracted[4] && <>(vcyl_retracted && (hcyl_extended[0] || hcyl_extended[1] || hcyl_extended[2] || hcyl_extended[3] || hcyl_extended[4]))))) ) }
ltl order5_MUST_BE_FALSE { X( [](wp[5] -> <>(vcyl_extended && suction_on && carrying_wp && <>(wp_output && vcyl_extended && hcyl_retracted[0] && hcyl_retracted[1] && hcyl_retracted[2] && hcyl_retracted[3] && hcyl_retracted[4] && <>(vcyl_retracted && (hcyl_extended[0] || hcyl_extended[1] || hcyl_extended[2] || hcyl_extended[3] || hcyl_extended[4]))))) ) }
ltl order6_MUST_BE_FALSE { X( [](wp[6] -> <>(vcyl_extended && suction_on && carrying_wp && <>(wp_output && vcyl_extended && hcyl_retracted[0] && hcyl_retracted[1] && hcyl_retracted[2] && hcyl_retracted[3] && hcyl_retracted[4] && <>(vcyl_retracted && (hcyl_extended[0] || hcyl_extended[1] || hcyl_extended[2] || hcyl_extended[3] || hcyl_extended[4]))))) ) }
ltl order7_MUST_BE_FALSE { X( [](wp[7] -> <>(vcyl_extended && suction_on && carrying_wp && <>(wp_output && vcyl_extended && hcyl_retracted[0] && hcyl_retracted[1] && hcyl_retracted[2] && hcyl_retracted[3] && hcyl_retracted[4] && <>(vcyl_retracted && (hcyl_extended[0] || hcyl_extended[1] || hcyl_extended[2] || hcyl_extended[3] || hcyl_extended[4]))))) ) }
ltl order8_MUST_BE_FALSE { X( [](wp[8] -> <>(vcyl_extended && suction_on && carrying_wp && <>(wp_output && vcyl_extended && hcyl_retracted[0] && hcyl_retracted[1] && hcyl_retracted[2] && hcyl_retracted[3] && hcyl_retracted[4] && <>(vcyl_retracted && (hcyl_extended[0] || hcyl_extended[1] || hcyl_extended[2] || hcyl_extended[3] || hcyl_extended[4]))))) ) }
ltl order9_MUST_BE_FALSE { X( [](wp[9] -> <>(vcyl_extended && suction_on && carrying_wp && <>(wp_output && vcyl_extended && hcyl_retracted[0] && hcyl_retracted[1] && hcyl_retracted[2] && hcyl_retracted[3] && hcyl_retracted[4] && <>(vcyl_retracted && (hcyl_extended[0] || hcyl_extended[1] || hcyl_extended[2] || hcyl_extended[3] || hcyl_extended[4]))))) ) }
ltl order10_MUST_BE_FALSE { X( [](wp[10] -> <>(vcyl_extended && suction_on && carrying_wp && <>(wp_output && vcyl_extended && hcyl_retracted[0] && hcyl_retracted[1] && hcyl_retracted[2] && hcyl_retracted[3] && hcyl_retracted[4] && <>(vcyl_retracted && (hcyl_extended[0] || hcyl_extended[1] || hcyl_extended[2] || hcyl_extended[3] || hcyl_extended[4]))))) ) }
ltl order11_MUST_BE_FALSE { X( [](wp[11] -> <>(vcyl_extended && suction_on && carrying_wp && <>(wp_output && vcyl_extended && hcyl_retracted[0] && hcyl_retracted[1] && hcyl_retracted[2] && hcyl_retracted[3] && hcyl_retracted[4] && <>(vcyl_retracted && (hcyl_extended[0] || hcyl_extended[1] || hcyl_extended[2] || hcyl_extended[3] || hcyl_extended[4]))))) ) }
ltl order12_MUST_BE_FALSE { X( [](wp[12] -> <>(vcyl_extended && suction_on && carrying_wp && <>(wp_output && vcyl_extended && hcyl_retracted[0] && hcyl_retracted[1] && hcyl_retracted[2] && hcyl_retracted[3] && hcyl_retracted[4] && <>(vcyl_retracted && (hcyl_extended[0] || hcyl_extended[1] || hcyl_extended[2] || hcyl_extended[3] || hcyl_extended[4]))))) ) }
ltl order13_MUST_BE_FALSE { X( [](wp[13] -> <>(vcyl_extended && suction_on && carrying_wp && <>(wp_output && vcyl_extended && hcyl_retracted[0] && hcyl_retracted[1] && hcyl_retracted[2] && hcyl_retracted[3] && hcyl_retracted[4] && <>(vcyl_retracted && (hcyl_extended[0] || hcyl_extended[1] || hcyl_extended[2] || hcyl_extended[3] || hcyl_extended[4]))))) ) }
ltl order14_MUST_BE_FALSE { X( [](wp[14] -> <>(vcyl_extended && suction_on && carrying_wp && <>(wp_output && vcyl_extended && hcyl_retracted[0] && hcyl_retracted[1] && hcyl_retracted[2] && hcyl_retracted[3] && hcyl_retracted[4] && <>(vcyl_retracted && (hcyl_extended[0] || hcyl_extended[1] || hcyl_extended[2] || hcyl_extended[3] || hcyl_extended[4]))))) ) }
ltl order15_MUST_BE_FALSE { X( [](wp[15] -> <>(vcyl_extended && suction_on && carrying_wp && <>(wp_output && vcyl_extended && hcyl_retracted[0] && hcyl_retracted[1] && hcyl_retracted[2] && hcyl_retracted[3] && hcyl_retracted[4] && <>(vcyl_retracted && (hcyl_extended[0] || hcyl_extended[1] || hcyl_extended[2] || hcyl_extended[3] || hcyl_extended[4]))))) ) }
ltl order16_MUST_BE_FALSE { X( [](wp[16] -> <>(vcyl_extended && suction_on && carrying_wp && <>(wp_output && vcyl_extended && hcyl_retracted[0] && hcyl_retracted[1] && hcyl_retracted[2] && hcyl_retracted[3] && hcyl_retracted[4] && <>(vcyl_retracted && (hcyl_extended[0] || hcyl_extended[1] || hcyl_extended[2] || hcyl_extended[3] || hcyl_extended[4]))))) ) }
ltl order17_MUST_BE_FALSE { X( [](wp[17] -> <>(vcyl_extended && suction_on && carrying_wp && <>(wp_output && vcyl_extended && hcyl_retracted[0] && hcyl_retracted[1] && hcyl_retracted[2] && hcyl_retracted[3] && hcyl_retracted[4] && <>(vcyl_retracted && (hcyl_extended[0] || hcyl_extended[1] || hcyl_extended[2] || hcyl_extended[3] || hcyl_extended[4]))))) ) }
ltl order18_MUST_BE_FALSE { X( [](wp[18] -> <>(vcyl_extended && suction_on && carrying_wp && <>(wp_output && vcyl_extended && hcyl_retracted[0] && hcyl_retracted[1] && hcyl_retracted[2] && hcyl_retracted[3] && hcyl_retracted[4] && <>(vcyl_retracted && (hcyl_extended[0] || hcyl_extended[1] || hcyl_extended[2] || hcyl_extended[3] || hcyl_extended[4]))))) ) }
ltl order19_MUST_BE_FALSE { X( [](wp[19] -> <>(vcyl_extended && suction_on && carrying_wp && <>(wp_output && vcyl_extended && hcyl_retracted[0] && hcyl_retracted[1] && hcyl_retracted[2] && hcyl_retracted[3] && hcyl_retracted[4] && <>(vcyl_retracted && (hcyl_extended[0] || hcyl_extended[1] || hcyl_extended[2] || hcyl_extended[3] || hcyl_extended[4]))))) ) }
ltl order20_MUST_BE_FALSE { X( [](wp[20] -> <>(vcyl_extended && suction_on && carrying_wp && <>(wp_output && vcyl_extended && hcyl_retracted[0] && hcyl_retracted[1] && hcyl_retracted[2] && hcyl_retracted[3] && hcyl_retracted[4] && <>(vcyl_retracted && (hcyl_extended[0] || hcyl_extended[1] || hcyl_extended[2] || hcyl_extended[3] || hcyl_extended[4]))))) ) }
ltl order21_MUST_BE_FALSE { X( [](wp[21] -> <>(vcyl_extended && suction_on && carrying_wp && <>(wp_output && vcyl_extended && hcyl_retracted[0] && hcyl_retracted[1] && hcyl_retracted[2] && hcyl_retracted[3] && hcyl_retracted[4] && <>(vcyl_retracted && (hcyl_extended[0] || hcyl_extended[1] || hcyl_extended[2] || hcyl_extended[3] || hcyl_extended[4]))))) ) }
ltl order22_MUST_BE_FALSE { X( [](wp[22] -> <>(vcyl_extended && suction_on && carrying_wp && <>(wp_output && vcyl_extended && hcyl_retracted[0] && hcyl_retracted[1] && hcyl_retracted[2] && hcyl_retracted[3] && hcyl_retracted[4] && <>(vcyl_retracted && (hcyl_extended[0] || hcyl_extended[1] || hcyl_extended[2] || hcyl_extended[3] || hcyl_extended[4]))))) ) }
ltl order23_MUST_BE_FALSE { X( [](wp[23] -> <>(vcyl_extended && suction_on && carrying_wp && <>(wp_output && vcyl_extended && hcyl_retracted[0] && hcyl_retracted[1] && hcyl_retracted[2] && hcyl_retracted[3] && hcyl_retracted[4] && <>(vcyl_retracted && (hcyl_extended[0] || hcyl_extended[1] || hcyl_extended[2] || hcyl_extended[3] || hcyl_extended[4]))))) ) }
ltl order24_MUST_BE_FALSE { X( [](wp[24] -> <>(vcyl_extended && suction_on && carrying_wp && <>(wp_output && vcyl_extended && hcyl_retracted[0] && hcyl_retracted[1] && hcyl_retracted[2] && hcyl_retracted[3] && hcyl_retracted[4] && <>(vcyl_retracted && (hcyl_extended[0] || hcyl_extended[1] || hcyl_extended[2] || hcyl_extended[3] || hcyl_extended[4]))))) ) }
ltl order25_MUST_BE_FALSE { X( [](wp[25] -> <>(vcyl_extended && suction_on && carrying_wp && <>(wp_output && vcyl_extended && hcyl_retracted[0] && hcyl_retracted[1] && hcyl_retracted[2] && hcyl_retracted[3] && hcyl_retracted[4] && <>(vcyl_retracted && (hcyl_extended[0] || hcyl_extended[1] || hcyl_extended[2] || hcyl_extended[3] || hcyl_extended[4]))))) ) }
ltl order26_MUST_BE_FALSE { X( [](wp[26] -> <>(vcyl_extended && suction_on && carrying_wp && <>(wp_output && vcyl_extended && hcyl_retracted[0] && hcyl_retracted[1] && hcyl_retracted[2] && hcyl_retracted[3] && hcyl_retracted[4] && <>(vcyl_retracted && (hcyl_extended[0] || hcyl_extended[1] || hcyl_extended[2] || hcyl_extended[3] || hcyl_extended[4]))))) ) }
ltl order27_MUST_BE_FALSE { X( [](wp[27] -> <>(vcyl_extended && suction_on && carrying_wp && <>(wp_output && vcyl_extended && hcyl_retracted[0] && hcyl_retracted[1] && hcyl_retracted[2] && hcyl_retracted[3] && hcyl_retracted[4] && <>(vcyl_retracted && (hcyl_extended[0] || hcyl_extended[1] || hcyl_extended[2] || hcyl_extended[3] || hcyl_extended[4]))))) ) }
ltl order28_MUST_BE_FALSE { X( [](wp[28] -> <>(vcyl_extended && suction_on && carrying_wp && <>(wp_output && vcyl_extended && hcyl_retracted[0] && hcyl_retracted[1] && hcyl_retracted[2] && hcyl_retracted[3] && hcyl_retracted[4] && <>(vcyl_retracted && (hcyl_extended[0] || hcyl_extended[1] || hcyl_extended[2] || hcyl_extended[3] || hcyl_extended[4]))))) ) }
ltl order29_MUST_BE_FALSE { X( [](wp[29] -> <>(vcyl_extended && suction_on && carrying_wp && <>(wp_output && vcyl_extended && hcyl_retracted[0] && hcyl_retracted[1] && hcyl_retracted[2] && hcyl_retracted[3] && hcyl_retracted[4] && <>(vcyl_retracted && (hcyl_extended[0] || hcyl_extended[1] || hcyl_extended[2] || hcyl_extended[3] || hcyl_extended[4]))))) ) }
ltl order30_MUST_BE_FALSE { X( [](wp[30] -> <>(vcyl_extended && suction_on && carrying_wp && <>(wp_output && vcyl_extended && hcyl_retracted[0] && hcyl_retracted[1] && hcyl_retracted[2] && hcyl_retracted[3] && hcyl_retracted[4] && <>(vcyl_retracted && (hcyl_extended[0] || hcyl_extended[1] || hcyl_extended[2] || hcyl_extended[3] || hcyl_extended[4]))))) ) }

ltl disappear0_MUST_BE_FALSE { X( []((wp[0] && !adding_wp[0]) -> <> !wp[0]) ) }
ltl disappear1_MUST_BE_FALSE { X( []((wp[1] && !adding_wp[1]) -> <> !wp[1]) ) }
ltl disappear2_MUST_BE_FALSE { X( []((wp[2] && !adding_wp[2]) -> <> !wp[2]) ) }
ltl disappear3_MUST_BE_FALSE { X( []((wp[3] && !adding_wp[3]) -> <> !wp[3]) ) }
ltl disappear4_MUST_BE_FALSE { X( []((wp[4] && !adding_wp[4]) -> <> !wp[4]) ) }
ltl disappear5_MUST_BE_FALSE { X( []((wp[5] && !adding_wp[5]) -> <> !wp[5]) ) }
ltl disappear6_MUST_BE_FALSE { X( []((wp[6] && !adding_wp[6]) -> <> !wp[6]) ) }
ltl disappear7_MUST_BE_FALSE { X( []((wp[7] && !adding_wp[7]) -> <> !wp[7]) ) }
ltl disappear8_MUST_BE_FALSE { X( []((wp[8] && !adding_wp[8]) -> <> !wp[8]) ) }
ltl disappear9_MUST_BE_FALSE { X( []((wp[9] && !adding_wp[9]) -> <> !wp[9]) ) }
ltl disappear10_MUST_BE_FALSE { X( []((wp[10] && !adding_wp[10]) -> <> !wp[10]) ) }
ltl disappear11_MUST_BE_FALSE { X( []((wp[11] && !adding_wp[11]) -> <> !wp[11]) ) }
ltl disappear12_MUST_BE_FALSE { X( []((wp[12] && !adding_wp[12]) -> <> !wp[12]) ) }
ltl disappear13_MUST_BE_FALSE { X( []((wp[13] && !adding_wp[13]) -> <> !wp[13]) ) }
ltl disappear14_MUST_BE_FALSE { X( []((wp[14] && !adding_wp[14]) -> <> !wp[14]) ) }
ltl disappear15_MUST_BE_FALSE { X( []((wp[15] && !adding_wp[15]) -> <> !wp[15]) ) }
ltl disappear16_MUST_BE_FALSE { X( []((wp[16] && !adding_wp[16]) -> <> !wp[16]) ) }
ltl disappear17_MUST_BE_FALSE { X( []((wp[17] && !adding_wp[17]) -> <> !wp[17]) ) }
ltl disappear18_MUST_BE_FALSE { X( []((wp[18] && !adding_wp[18]) -> <> !wp[18]) ) }
ltl disappear19_MUST_BE_FALSE { X( []((wp[19] && !adding_wp[19]) -> <> !wp[19]) ) }
ltl disappear20_MUST_BE_FALSE { X( []((wp[20] && !adding_wp[20]) -> <> !wp[20]) ) }
ltl disappear21_MUST_BE_FALSE { X( []((wp[21] && !adding_wp[21]) -> <> !wp[21]) ) }
ltl disappear22_MUST_BE_FALSE { X( []((wp[22] && !adding_wp[22]) -> <> !wp[22]) ) }
ltl disappear23_MUST_BE_FALSE { X( []((wp[23] && !adding_wp[23]) -> <> !wp[23]) ) }
ltl disappear24_MUST_BE_FALSE { X( []((wp[24] && !adding_wp[24]) -> <> !wp[24]) ) }
ltl disappear25_MUST_BE_FALSE { X( []((wp[25] && !adding_wp[25]) -> <> !wp[25]) ) }
ltl disappear26_MUST_BE_FALSE { X( []((wp[26] && !adding_wp[26]) -> <> !wp[26]) ) }
ltl disappear27_MUST_BE_FALSE { X( []((wp[27] && !adding_wp[27]) -> <> !wp[27]) ) }
ltl disappear28_MUST_BE_FALSE { X( []((wp[28] && !adding_wp[28]) -> <> !wp[28]) ) }
ltl disappear29_MUST_BE_FALSE { X( []((wp[29] && !adding_wp[29]) -> <> !wp[29]) ) }
ltl disappear30_MUST_BE_FALSE { X( []((wp[30] && !adding_wp[30]) -> <> !wp[30]) ) }

ltl additional0_MUST_BE_FALSE { X( [](carrying_wp -> suction_on) ) }
ltl additional1_MUST_BE_FALSE { X( [](suction_on -> (wp[0] || wp[1] || wp[2] || wp[3] || wp[4])) ) }
ltl additional2_MUST_BE_FALSE { X( [](suction_on -> carrying_wp) ) }
