ltl order0_MUST_BE_TRUE { X( [](wp[0] -> <>(vcyl_extended && suction_on && carrying_wp && <>(wp_output && vcyl_extended && hcyl_retracted[0] && hcyl_retracted[1] && hcyl_retracted[2] && hcyl_retracted[3] && hcyl_retracted[4] && <>(vcyl_retracted && hcyl_retracted[0] && hcyl_retracted[1] && hcyl_retracted[2] && hcyl_retracted[3] && hcyl_retracted[4])))) ) }
ltl order1_MUST_BE_TRUE { X( [](wp[1] -> <>(vcyl_extended && suction_on && carrying_wp && <>(wp_output && vcyl_extended && hcyl_retracted[0] && hcyl_retracted[1] && hcyl_retracted[2] && hcyl_retracted[3] && hcyl_retracted[4] && <>(vcyl_retracted && hcyl_retracted[0] && hcyl_retracted[1] && hcyl_retracted[2] && hcyl_retracted[3] && hcyl_retracted[4])))) ) }
ltl order2_MUST_BE_TRUE { X( [](wp[2] -> <>(vcyl_extended && suction_on && carrying_wp && <>(wp_output && vcyl_extended && hcyl_retracted[0] && hcyl_retracted[1] && hcyl_retracted[2] && hcyl_retracted[3] && hcyl_retracted[4] && <>(vcyl_retracted && hcyl_retracted[0] && hcyl_retracted[1] && hcyl_retracted[2] && hcyl_retracted[3] && hcyl_retracted[4])))) ) }
ltl order3_MUST_BE_TRUE { X( [](wp[3] -> <>(vcyl_extended && suction_on && carrying_wp && <>(wp_output && vcyl_extended && hcyl_retracted[0] && hcyl_retracted[1] && hcyl_retracted[2] && hcyl_retracted[3] && hcyl_retracted[4] && <>(vcyl_retracted && hcyl_retracted[0] && hcyl_retracted[1] && hcyl_retracted[2] && hcyl_retracted[3] && hcyl_retracted[4])))) ) }
ltl order4_MUST_BE_TRUE { X( [](wp[4] -> <>(vcyl_extended && suction_on && carrying_wp && <>(wp_output && vcyl_extended && hcyl_retracted[0] && hcyl_retracted[1] && hcyl_retracted[2] && hcyl_retracted[3] && hcyl_retracted[4] && <>(vcyl_retracted && hcyl_retracted[0] && hcyl_retracted[1] && hcyl_retracted[2] && hcyl_retracted[3] && hcyl_retracted[4])))) ) }
ltl order5_MUST_BE_TRUE { X( [](wp[5] -> <>(vcyl_extended && suction_on && carrying_wp && <>(wp_output && vcyl_extended && hcyl_retracted[0] && hcyl_retracted[1] && hcyl_retracted[2] && hcyl_retracted[3] && hcyl_retracted[4] && <>(vcyl_retracted && hcyl_retracted[0] && hcyl_retracted[1] && hcyl_retracted[2] && hcyl_retracted[3] && hcyl_retracted[4])))) ) }
ltl order6_MUST_BE_TRUE { X( [](wp[6] -> <>(vcyl_extended && suction_on && carrying_wp && <>(wp_output && vcyl_extended && hcyl_retracted[0] && hcyl_retracted[1] && hcyl_retracted[2] && hcyl_retracted[3] && hcyl_retracted[4] && <>(vcyl_retracted && hcyl_retracted[0] && hcyl_retracted[1] && hcyl_retracted[2] && hcyl_retracted[3] && hcyl_retracted[4])))) ) }
ltl order7_MUST_BE_TRUE { X( [](wp[7] -> <>(vcyl_extended && suction_on && carrying_wp && <>(wp_output && vcyl_extended && hcyl_retracted[0] && hcyl_retracted[1] && hcyl_retracted[2] && hcyl_retracted[3] && hcyl_retracted[4] && <>(vcyl_retracted && hcyl_retracted[0] && hcyl_retracted[1] && hcyl_retracted[2] && hcyl_retracted[3] && hcyl_retracted[4])))) ) }
ltl order8_MUST_BE_TRUE { X( [](wp[8] -> <>(vcyl_extended && suction_on && carrying_wp && <>(wp_output && vcyl_extended && hcyl_retracted[0] && hcyl_retracted[1] && hcyl_retracted[2] && hcyl_retracted[3] && hcyl_retracted[4] && <>(vcyl_retracted && hcyl_retracted[0] && hcyl_retracted[1] && hcyl_retracted[2] && hcyl_retracted[3] && hcyl_retracted[4])))) ) }
ltl order9_MUST_BE_TRUE { X( [](wp[9] -> <>(vcyl_extended && suction_on && carrying_wp && <>(wp_output && vcyl_extended && hcyl_retracted[0] && hcyl_retracted[1] && hcyl_retracted[2] && hcyl_retracted[3] && hcyl_retracted[4] && <>(vcyl_retracted && hcyl_retracted[0] && hcyl_retracted[1] && hcyl_retracted[2] && hcyl_retracted[3] && hcyl_retracted[4])))) ) }
ltl order10_MUST_BE_TRUE { X( [](wp[10] -> <>(vcyl_extended && suction_on && carrying_wp && <>(wp_output && vcyl_extended && hcyl_retracted[0] && hcyl_retracted[1] && hcyl_retracted[2] && hcyl_retracted[3] && hcyl_retracted[4] && <>(vcyl_retracted && hcyl_retracted[0] && hcyl_retracted[1] && hcyl_retracted[2] && hcyl_retracted[3] && hcyl_retracted[4])))) ) }
ltl order11_MUST_BE_TRUE { X( [](wp[11] -> <>(vcyl_extended && suction_on && carrying_wp && <>(wp_output && vcyl_extended && hcyl_retracted[0] && hcyl_retracted[1] && hcyl_retracted[2] && hcyl_retracted[3] && hcyl_retracted[4] && <>(vcyl_retracted && hcyl_retracted[0] && hcyl_retracted[1] && hcyl_retracted[2] && hcyl_retracted[3] && hcyl_retracted[4])))) ) }
ltl order12_MUST_BE_TRUE { X( [](wp[12] -> <>(vcyl_extended && suction_on && carrying_wp && <>(wp_output && vcyl_extended && hcyl_retracted[0] && hcyl_retracted[1] && hcyl_retracted[2] && hcyl_retracted[3] && hcyl_retracted[4] && <>(vcyl_retracted && hcyl_retracted[0] && hcyl_retracted[1] && hcyl_retracted[2] && hcyl_retracted[3] && hcyl_retracted[4])))) ) }
ltl order13_MUST_BE_TRUE { X( [](wp[13] -> <>(vcyl_extended && suction_on && carrying_wp && <>(wp_output && vcyl_extended && hcyl_retracted[0] && hcyl_retracted[1] && hcyl_retracted[2] && hcyl_retracted[3] && hcyl_retracted[4] && <>(vcyl_retracted && hcyl_retracted[0] && hcyl_retracted[1] && hcyl_retracted[2] && hcyl_retracted[3] && hcyl_retracted[4])))) ) }
ltl order14_MUST_BE_TRUE { X( [](wp[14] -> <>(vcyl_extended && suction_on && carrying_wp && <>(wp_output && vcyl_extended && hcyl_retracted[0] && hcyl_retracted[1] && hcyl_retracted[2] && hcyl_retracted[3] && hcyl_retracted[4] && <>(vcyl_retracted && hcyl_retracted[0] && hcyl_retracted[1] && hcyl_retracted[2] && hcyl_retracted[3] && hcyl_retracted[4])))) ) }
ltl order15_MUST_BE_TRUE { X( [](wp[15] -> <>(vcyl_extended && suction_on && carrying_wp && <>(wp_output && vcyl_extended && hcyl_retracted[0] && hcyl_retracted[1] && hcyl_retracted[2] && hcyl_retracted[3] && hcyl_retracted[4] && <>(vcyl_retracted && hcyl_retracted[0] && hcyl_retracted[1] && hcyl_retracted[2] && hcyl_retracted[3] && hcyl_retracted[4])))) ) }
ltl order16_MUST_BE_TRUE { X( [](wp[16] -> <>(vcyl_extended && suction_on && carrying_wp && <>(wp_output && vcyl_extended && hcyl_retracted[0] && hcyl_retracted[1] && hcyl_retracted[2] && hcyl_retracted[3] && hcyl_retracted[4] && <>(vcyl_retracted && hcyl_retracted[0] && hcyl_retracted[1] && hcyl_retracted[2] && hcyl_retracted[3] && hcyl_retracted[4])))) ) }
ltl order17_MUST_BE_TRUE { X( [](wp[17] -> <>(vcyl_extended && suction_on && carrying_wp && <>(wp_output && vcyl_extended && hcyl_retracted[0] && hcyl_retracted[1] && hcyl_retracted[2] && hcyl_retracted[3] && hcyl_retracted[4] && <>(vcyl_retracted && hcyl_retracted[0] && hcyl_retracted[1] && hcyl_retracted[2] && hcyl_retracted[3] && hcyl_retracted[4])))) ) }
ltl order18_MUST_BE_TRUE { X( [](wp[18] -> <>(vcyl_extended && suction_on && carrying_wp && <>(wp_output && vcyl_extended && hcyl_retracted[0] && hcyl_retracted[1] && hcyl_retracted[2] && hcyl_retracted[3] && hcyl_retracted[4] && <>(vcyl_retracted && hcyl_retracted[0] && hcyl_retracted[1] && hcyl_retracted[2] && hcyl_retracted[3] && hcyl_retracted[4])))) ) }
ltl order19_MUST_BE_TRUE { X( [](wp[19] -> <>(vcyl_extended && suction_on && carrying_wp && <>(wp_output && vcyl_extended && hcyl_retracted[0] && hcyl_retracted[1] && hcyl_retracted[2] && hcyl_retracted[3] && hcyl_retracted[4] && <>(vcyl_retracted && hcyl_retracted[0] && hcyl_retracted[1] && hcyl_retracted[2] && hcyl_retracted[3] && hcyl_retracted[4])))) ) }
ltl order20_MUST_BE_TRUE { X( [](wp[20] -> <>(vcyl_extended && suction_on && carrying_wp && <>(wp_output && vcyl_extended && hcyl_retracted[0] && hcyl_retracted[1] && hcyl_retracted[2] && hcyl_retracted[3] && hcyl_retracted[4] && <>(vcyl_retracted && hcyl_retracted[0] && hcyl_retracted[1] && hcyl_retracted[2] && hcyl_retracted[3] && hcyl_retracted[4])))) ) }
ltl order21_MUST_BE_TRUE { X( [](wp[21] -> <>(vcyl_extended && suction_on && carrying_wp && <>(wp_output && vcyl_extended && hcyl_retracted[0] && hcyl_retracted[1] && hcyl_retracted[2] && hcyl_retracted[3] && hcyl_retracted[4] && <>(vcyl_retracted && hcyl_retracted[0] && hcyl_retracted[1] && hcyl_retracted[2] && hcyl_retracted[3] && hcyl_retracted[4])))) ) }
ltl order22_MUST_BE_TRUE { X( [](wp[22] -> <>(vcyl_extended && suction_on && carrying_wp && <>(wp_output && vcyl_extended && hcyl_retracted[0] && hcyl_retracted[1] && hcyl_retracted[2] && hcyl_retracted[3] && hcyl_retracted[4] && <>(vcyl_retracted && hcyl_retracted[0] && hcyl_retracted[1] && hcyl_retracted[2] && hcyl_retracted[3] && hcyl_retracted[4])))) ) }
ltl order23_MUST_BE_TRUE { X( [](wp[23] -> <>(vcyl_extended && suction_on && carrying_wp && <>(wp_output && vcyl_extended && hcyl_retracted[0] && hcyl_retracted[1] && hcyl_retracted[2] && hcyl_retracted[3] && hcyl_retracted[4] && <>(vcyl_retracted && hcyl_retracted[0] && hcyl_retracted[1] && hcyl_retracted[2] && hcyl_retracted[3] && hcyl_retracted[4])))) ) }
ltl order24_MUST_BE_TRUE { X( [](wp[24] -> <>(vcyl_extended && suction_on && carrying_wp && <>(wp_output && vcyl_extended && hcyl_retracted[0] && hcyl_retracted[1] && hcyl_retracted[2] && hcyl_retracted[3] && hcyl_retracted[4] && <>(vcyl_retracted && hcyl_retracted[0] && hcyl_retracted[1] && hcyl_retracted[2] && hcyl_retracted[3] && hcyl_retracted[4])))) ) }
ltl order25_MUST_BE_TRUE { X( [](wp[25] -> <>(vcyl_extended && suction_on && carrying_wp && <>(wp_output && vcyl_extended && hcyl_retracted[0] && hcyl_retracted[1] && hcyl_retracted[2] && hcyl_retracted[3] && hcyl_retracted[4] && <>(vcyl_retracted && hcyl_retracted[0] && hcyl_retracted[1] && hcyl_retracted[2] && hcyl_retracted[3] && hcyl_retracted[4])))) ) }
ltl order26_MUST_BE_TRUE { X( [](wp[26] -> <>(vcyl_extended && suction_on && carrying_wp && <>(wp_output && vcyl_extended && hcyl_retracted[0] && hcyl_retracted[1] && hcyl_retracted[2] && hcyl_retracted[3] && hcyl_retracted[4] && <>(vcyl_retracted && hcyl_retracted[0] && hcyl_retracted[1] && hcyl_retracted[2] && hcyl_retracted[3] && hcyl_retracted[4])))) ) }
ltl order27_MUST_BE_TRUE { X( [](wp[27] -> <>(vcyl_extended && suction_on && carrying_wp && <>(wp_output && vcyl_extended && hcyl_retracted[0] && hcyl_retracted[1] && hcyl_retracted[2] && hcyl_retracted[3] && hcyl_retracted[4] && <>(vcyl_retracted && hcyl_retracted[0] && hcyl_retracted[1] && hcyl_retracted[2] && hcyl_retracted[3] && hcyl_retracted[4])))) ) }
ltl order28_MUST_BE_TRUE { X( [](wp[28] -> <>(vcyl_extended && suction_on && carrying_wp && <>(wp_output && vcyl_extended && hcyl_retracted[0] && hcyl_retracted[1] && hcyl_retracted[2] && hcyl_retracted[3] && hcyl_retracted[4] && <>(vcyl_retracted && hcyl_retracted[0] && hcyl_retracted[1] && hcyl_retracted[2] && hcyl_retracted[3] && hcyl_retracted[4])))) ) }
ltl order29_MUST_BE_TRUE { X( [](wp[29] -> <>(vcyl_extended && suction_on && carrying_wp && <>(wp_output && vcyl_extended && hcyl_retracted[0] && hcyl_retracted[1] && hcyl_retracted[2] && hcyl_retracted[3] && hcyl_retracted[4] && <>(vcyl_retracted && hcyl_retracted[0] && hcyl_retracted[1] && hcyl_retracted[2] && hcyl_retracted[3] && hcyl_retracted[4])))) ) }
ltl order30_MUST_BE_TRUE { X( [](wp[30] -> <>(vcyl_extended && suction_on && carrying_wp && <>(wp_output && vcyl_extended && hcyl_retracted[0] && hcyl_retracted[1] && hcyl_retracted[2] && hcyl_retracted[3] && hcyl_retracted[4] && <>(vcyl_retracted && hcyl_retracted[0] && hcyl_retracted[1] && hcyl_retracted[2] && hcyl_retracted[3] && hcyl_retracted[4])))) ) }

ltl disappear0_MUST_BE_TRUE { X( []((wp[0] && !adding_wp[0]) -> <>(!wp[0] || adding_wp[0])) ) }
ltl disappear1_MUST_BE_TRUE { X( []((wp[1] && !adding_wp[1]) -> <>(!wp[1] || adding_wp[0] || adding_wp[1])) ) }
ltl disappear2_MUST_BE_TRUE { X( []((wp[2] && !adding_wp[2]) -> <>(!wp[2] || adding_wp[0] || adding_wp[1] || adding_wp[2])) ) }
ltl disappear3_MUST_BE_TRUE { X( []((wp[3] && !adding_wp[3]) -> <>(!wp[3] || adding_wp[0] || adding_wp[1] || adding_wp[2] || adding_wp[3])) ) }
ltl disappear4_MUST_BE_TRUE { X( []((wp[4] && !adding_wp[4]) -> <>(!wp[4] || adding_wp[0] || adding_wp[1] || adding_wp[2] || adding_wp[3] || adding_wp[4])) ) }
ltl disappear5_MUST_BE_TRUE { X( []((wp[5] && !adding_wp[5]) -> <>(!wp[5] || adding_wp[0] || adding_wp[1] || adding_wp[2] || adding_wp[3] || adding_wp[4] || adding_wp[5])) ) }
ltl disappear6_MUST_BE_TRUE { X( []((wp[6] && !adding_wp[6]) -> <>(!wp[6] || adding_wp[0] || adding_wp[1] || adding_wp[2] || adding_wp[3] || adding_wp[4] || adding_wp[5] || adding_wp[6])) ) }
ltl disappear7_MUST_BE_TRUE { X( []((wp[7] && !adding_wp[7]) -> <>(!wp[7] || adding_wp[0] || adding_wp[1] || adding_wp[2] || adding_wp[3] || adding_wp[4] || adding_wp[5] || adding_wp[6] || adding_wp[7])) ) }
ltl disappear8_MUST_BE_TRUE { X( []((wp[8] && !adding_wp[8]) -> <>(!wp[8] || adding_wp[0] || adding_wp[1] || adding_wp[2] || adding_wp[3] || adding_wp[4] || adding_wp[5] || adding_wp[6] || adding_wp[7] || adding_wp[8])) ) }
ltl disappear9_MUST_BE_TRUE { X( []((wp[9] && !adding_wp[9]) -> <>(!wp[9] || adding_wp[0] || adding_wp[1] || adding_wp[2] || adding_wp[3] || adding_wp[4] || adding_wp[5] || adding_wp[6] || adding_wp[7] || adding_wp[8] || adding_wp[9])) ) }
ltl disappear10_MUST_BE_TRUE { X( []((wp[10] && !adding_wp[10]) -> <>(!wp[10] || adding_wp[0] || adding_wp[1] || adding_wp[2] || adding_wp[3] || adding_wp[4] || adding_wp[5] || adding_wp[6] || adding_wp[7] || adding_wp[8] || adding_wp[9] || adding_wp[10])) ) }
ltl disappear11_MUST_BE_TRUE { X( []((wp[11] && !adding_wp[11]) -> <>(!wp[11] || adding_wp[0] || adding_wp[1] || adding_wp[2] || adding_wp[3] || adding_wp[4] || adding_wp[5] || adding_wp[6] || adding_wp[7] || adding_wp[8] || adding_wp[9] || adding_wp[10] || adding_wp[11])) ) }
ltl disappear12_MUST_BE_TRUE { X( []((wp[12] && !adding_wp[12]) -> <>(!wp[12] || adding_wp[0] || adding_wp[1] || adding_wp[2] || adding_wp[3] || adding_wp[4] || adding_wp[5] || adding_wp[6] || adding_wp[7] || adding_wp[8] || adding_wp[9] || adding_wp[10] || adding_wp[11] || adding_wp[12])) ) }
ltl disappear13_MUST_BE_TRUE { X( []((wp[13] && !adding_wp[13]) -> <>(!wp[13] || adding_wp[0] || adding_wp[1] || adding_wp[2] || adding_wp[3] || adding_wp[4] || adding_wp[5] || adding_wp[6] || adding_wp[7] || adding_wp[8] || adding_wp[9] || adding_wp[10] || adding_wp[11] || adding_wp[12] || adding_wp[13])) ) }
ltl disappear14_MUST_BE_TRUE { X( []((wp[14] && !adding_wp[14]) -> <>(!wp[14] || adding_wp[0] || adding_wp[1] || adding_wp[2] || adding_wp[3] || adding_wp[4] || adding_wp[5] || adding_wp[6] || adding_wp[7] || adding_wp[8] || adding_wp[9] || adding_wp[10] || adding_wp[11] || adding_wp[12] || adding_wp[13] || adding_wp[14])) ) }
ltl disappear15_MUST_BE_TRUE { X( []((wp[15] && !adding_wp[15]) -> <>(!wp[15] || adding_wp[0] || adding_wp[1] || adding_wp[2] || adding_wp[3] || adding_wp[4] || adding_wp[5] || adding_wp[6] || adding_wp[7] || adding_wp[8] || adding_wp[9] || adding_wp[10] || adding_wp[11] || adding_wp[12] || adding_wp[13] || adding_wp[14] || adding_wp[15])) ) }
ltl disappear16_MUST_BE_TRUE { X( []((wp[16] && !adding_wp[16]) -> <>(!wp[16] || adding_wp[0] || adding_wp[1] || adding_wp[2] || adding_wp[3] || adding_wp[4] || adding_wp[5] || adding_wp[6] || adding_wp[7] || adding_wp[8] || adding_wp[9] || adding_wp[10] || adding_wp[11] || adding_wp[12] || adding_wp[13] || adding_wp[14] || adding_wp[15] || adding_wp[16])) ) }
ltl disappear17_MUST_BE_TRUE { X( []((wp[17] && !adding_wp[17]) -> <>(!wp[17] || adding_wp[0] || adding_wp[1] || adding_wp[2] || adding_wp[3] || adding_wp[4] || adding_wp[5] || adding_wp[6] || adding_wp[7] || adding_wp[8] || adding_wp[9] || adding_wp[10] || adding_wp[11] || adding_wp[12] || adding_wp[13] || adding_wp[14] || adding_wp[15] || adding_wp[16] || adding_wp[17])) ) }
ltl disappear18_MUST_BE_TRUE { X( []((wp[18] && !adding_wp[18]) -> <>(!wp[18] || adding_wp[0] || adding_wp[1] || adding_wp[2] || adding_wp[3] || adding_wp[4] || adding_wp[5] || adding_wp[6] || adding_wp[7] || adding_wp[8] || adding_wp[9] || adding_wp[10] || adding_wp[11] || adding_wp[12] || adding_wp[13] || adding_wp[14] || adding_wp[15] || adding_wp[16] || adding_wp[17] || adding_wp[18])) ) }
ltl disappear19_MUST_BE_TRUE { X( []((wp[19] && !adding_wp[19]) -> <>(!wp[19] || adding_wp[0] || adding_wp[1] || adding_wp[2] || adding_wp[3] || adding_wp[4] || adding_wp[5] || adding_wp[6] || adding_wp[7] || adding_wp[8] || adding_wp[9] || adding_wp[10] || adding_wp[11] || adding_wp[12] || adding_wp[13] || adding_wp[14] || adding_wp[15] || adding_wp[16] || adding_wp[17] || adding_wp[18] || adding_wp[19])) ) }
ltl disappear20_MUST_BE_TRUE { X( []((wp[20] && !adding_wp[20]) -> <>(!wp[20] || adding_wp[0] || adding_wp[1] || adding_wp[2] || adding_wp[3] || adding_wp[4] || adding_wp[5] || adding_wp[6] || adding_wp[7] || adding_wp[8] || adding_wp[9] || adding_wp[10] || adding_wp[11] || adding_wp[12] || adding_wp[13] || adding_wp[14] || adding_wp[15] || adding_wp[16] || adding_wp[17] || adding_wp[18] || adding_wp[19] || adding_wp[20])) ) }
ltl disappear21_MUST_BE_TRUE { X( []((wp[21] && !adding_wp[21]) -> <>(!wp[21] || adding_wp[0] || adding_wp[1] || adding_wp[2] || adding_wp[3] || adding_wp[4] || adding_wp[5] || adding_wp[6] || adding_wp[7] || adding_wp[8] || adding_wp[9] || adding_wp[10] || adding_wp[11] || adding_wp[12] || adding_wp[13] || adding_wp[14] || adding_wp[15] || adding_wp[16] || adding_wp[17] || adding_wp[18] || adding_wp[19] || adding_wp[20] || adding_wp[21])) ) }
ltl disappear22_MUST_BE_TRUE { X( []((wp[22] && !adding_wp[22]) -> <>(!wp[22] || adding_wp[0] || adding_wp[1] || adding_wp[2] || adding_wp[3] || adding_wp[4] || adding_wp[5] || adding_wp[6] || adding_wp[7] || adding_wp[8] || adding_wp[9] || adding_wp[10] || adding_wp[11] || adding_wp[12] || adding_wp[13] || adding_wp[14] || adding_wp[15] || adding_wp[16] || adding_wp[17] || adding_wp[18] || adding_wp[19] || adding_wp[20] || adding_wp[21] || adding_wp[22])) ) }
ltl disappear23_MUST_BE_TRUE { X( []((wp[23] && !adding_wp[23]) -> <>(!wp[23] || adding_wp[0] || adding_wp[1] || adding_wp[2] || adding_wp[3] || adding_wp[4] || adding_wp[5] || adding_wp[6] || adding_wp[7] || adding_wp[8] || adding_wp[9] || adding_wp[10] || adding_wp[11] || adding_wp[12] || adding_wp[13] || adding_wp[14] || adding_wp[15] || adding_wp[16] || adding_wp[17] || adding_wp[18] || adding_wp[19] || adding_wp[20] || adding_wp[21] || adding_wp[22] || adding_wp[23])) ) }
ltl disappear24_MUST_BE_TRUE { X( []((wp[24] && !adding_wp[24]) -> <>(!wp[24] || adding_wp[0] || adding_wp[1] || adding_wp[2] || adding_wp[3] || adding_wp[4] || adding_wp[5] || adding_wp[6] || adding_wp[7] || adding_wp[8] || adding_wp[9] || adding_wp[10] || adding_wp[11] || adding_wp[12] || adding_wp[13] || adding_wp[14] || adding_wp[15] || adding_wp[16] || adding_wp[17] || adding_wp[18] || adding_wp[19] || adding_wp[20] || adding_wp[21] || adding_wp[22] || adding_wp[23] || adding_wp[24])) ) }
ltl disappear25_MUST_BE_TRUE { X( []((wp[25] && !adding_wp[25]) -> <>(!wp[25] || adding_wp[0] || adding_wp[1] || adding_wp[2] || adding_wp[3] || adding_wp[4] || adding_wp[5] || adding_wp[6] || adding_wp[7] || adding_wp[8] || adding_wp[9] || adding_wp[10] || adding_wp[11] || adding_wp[12] || adding_wp[13] || adding_wp[14] || adding_wp[15] || adding_wp[16] || adding_wp[17] || adding_wp[18] || adding_wp[19] || adding_wp[20] || adding_wp[21] || adding_wp[22] || adding_wp[23] || adding_wp[24] || adding_wp[25])) ) }
ltl disappear26_MUST_BE_TRUE { X( []((wp[26] && !adding_wp[26]) -> <>(!wp[26] || adding_wp[0] || adding_wp[1] || adding_wp[2] || adding_wp[3] || adding_wp[4] || adding_wp[5] || adding_wp[6] || adding_wp[7] || adding_wp[8] || adding_wp[9] || adding_wp[10] || adding_wp[11] || adding_wp[12] || adding_wp[13] || adding_wp[14] || adding_wp[15] || adding_wp[16] || adding_wp[17] || adding_wp[18] || adding_wp[19] || adding_wp[20] || adding_wp[21] || adding_wp[22] || adding_wp[23] || adding_wp[24] || adding_wp[25] || adding_wp[26])) ) }
ltl disappear27_MUST_BE_TRUE { X( []((wp[27] && !adding_wp[27]) -> <>(!wp[27] || adding_wp[0] || adding_wp[1] || adding_wp[2] || adding_wp[3] || adding_wp[4] || adding_wp[5] || adding_wp[6] || adding_wp[7] || adding_wp[8] || adding_wp[9] || adding_wp[10] || adding_wp[11] || adding_wp[12] || adding_wp[13] || adding_wp[14] || adding_wp[15] || adding_wp[16] || adding_wp[17] || adding_wp[18] || adding_wp[19] || adding_wp[20] || adding_wp[21] || adding_wp[22] || adding_wp[23] || adding_wp[24] || adding_wp[25] || adding_wp[26] || adding_wp[27])) ) }
ltl disappear28_MUST_BE_TRUE { X( []((wp[28] && !adding_wp[28]) -> <>(!wp[28] || adding_wp[0] || adding_wp[1] || adding_wp[2] || adding_wp[3] || adding_wp[4] || adding_wp[5] || adding_wp[6] || adding_wp[7] || adding_wp[8] || adding_wp[9] || adding_wp[10] || adding_wp[11] || adding_wp[12] || adding_wp[13] || adding_wp[14] || adding_wp[15] || adding_wp[16] || adding_wp[17] || adding_wp[18] || adding_wp[19] || adding_wp[20] || adding_wp[21] || adding_wp[22] || adding_wp[23] || adding_wp[24] || adding_wp[25] || adding_wp[26] || adding_wp[27] || adding_wp[28])) ) }
ltl disappear29_MUST_BE_TRUE { X( []((wp[29] && !adding_wp[29]) -> <>(!wp[29] || adding_wp[0] || adding_wp[1] || adding_wp[2] || adding_wp[3] || adding_wp[4] || adding_wp[5] || adding_wp[6] || adding_wp[7] || adding_wp[8] || adding_wp[9] || adding_wp[10] || adding_wp[11] || adding_wp[12] || adding_wp[13] || adding_wp[14] || adding_wp[15] || adding_wp[16] || adding_wp[17] || adding_wp[18] || adding_wp[19] || adding_wp[20] || adding_wp[21] || adding_wp[22] || adding_wp[23] || adding_wp[24] || adding_wp[25] || adding_wp[26] || adding_wp[27] || adding_wp[28] || adding_wp[29])) ) }
ltl disappear30_MUST_BE_TRUE { X( []((wp[30] && !adding_wp[30]) -> <>(!wp[30] || adding_wp[0] || adding_wp[1] || adding_wp[2] || adding_wp[3] || adding_wp[4] || adding_wp[5] || adding_wp[6] || adding_wp[7] || adding_wp[8] || adding_wp[9] || adding_wp[10] || adding_wp[11] || adding_wp[12] || adding_wp[13] || adding_wp[14] || adding_wp[15] || adding_wp[16] || adding_wp[17] || adding_wp[18] || adding_wp[19] || adding_wp[20] || adding_wp[21] || adding_wp[22] || adding_wp[23] || adding_wp[24] || adding_wp[25] || adding_wp[26] || adding_wp[27] || adding_wp[28] || adding_wp[29] || adding_wp[30])) ) }

ltl spurious0_MUST_BE_TRUE { X( (!(!vcyl_retracted && (total_hcyl_pos == 1)) U (wp[0])) || ([] !(!vcyl_retracted && (total_hcyl_pos == 1))) ) }
ltl spurious1_MUST_BE_TRUE { X( (!(!vcyl_retracted && (total_hcyl_pos == 2)) U (wp[1])) || ([] !(!vcyl_retracted && (total_hcyl_pos == 2))) ) }
ltl spurious2_MUST_BE_TRUE { X( (!(!vcyl_retracted && (total_hcyl_pos == 3)) U (wp[2])) || ([] !(!vcyl_retracted && (total_hcyl_pos == 3))) ) }
ltl spurious3_MUST_BE_TRUE { X( (!(!vcyl_retracted && (total_hcyl_pos == 4)) U (wp[3])) || ([] !(!vcyl_retracted && (total_hcyl_pos == 4))) ) }
ltl spurious4_MUST_BE_TRUE { X( (!(!vcyl_retracted && (total_hcyl_pos == 5)) U (wp[4])) || ([] !(!vcyl_retracted && (total_hcyl_pos == 5))) ) }
ltl spurious5_MUST_BE_TRUE { X( (!(!vcyl_retracted && (total_hcyl_pos == 6)) U (wp[5])) || ([] !(!vcyl_retracted && (total_hcyl_pos == 6))) ) }
ltl spurious6_MUST_BE_TRUE { X( (!(!vcyl_retracted && (total_hcyl_pos == 7)) U (wp[6])) || ([] !(!vcyl_retracted && (total_hcyl_pos == 7))) ) }
ltl spurious7_MUST_BE_TRUE { X( (!(!vcyl_retracted && (total_hcyl_pos == 8)) U (wp[7])) || ([] !(!vcyl_retracted && (total_hcyl_pos == 8))) ) }
ltl spurious8_MUST_BE_TRUE { X( (!(!vcyl_retracted && (total_hcyl_pos == 9)) U (wp[8])) || ([] !(!vcyl_retracted && (total_hcyl_pos == 9))) ) }
ltl spurious9_MUST_BE_TRUE { X( (!(!vcyl_retracted && (total_hcyl_pos == 10)) U (wp[9])) || ([] !(!vcyl_retracted && (total_hcyl_pos == 10))) ) }
ltl spurious10_MUST_BE_TRUE { X( (!(!vcyl_retracted && (total_hcyl_pos == 11)) U (wp[10])) || ([] !(!vcyl_retracted && (total_hcyl_pos == 11))) ) }
ltl spurious11_MUST_BE_TRUE { X( (!(!vcyl_retracted && (total_hcyl_pos == 12)) U (wp[11])) || ([] !(!vcyl_retracted && (total_hcyl_pos == 12))) ) }
ltl spurious12_MUST_BE_TRUE { X( (!(!vcyl_retracted && (total_hcyl_pos == 13)) U (wp[12])) || ([] !(!vcyl_retracted && (total_hcyl_pos == 13))) ) }
ltl spurious13_MUST_BE_TRUE { X( (!(!vcyl_retracted && (total_hcyl_pos == 14)) U (wp[13])) || ([] !(!vcyl_retracted && (total_hcyl_pos == 14))) ) }
ltl spurious14_MUST_BE_TRUE { X( (!(!vcyl_retracted && (total_hcyl_pos == 15)) U (wp[14])) || ([] !(!vcyl_retracted && (total_hcyl_pos == 15))) ) }
ltl spurious15_MUST_BE_TRUE { X( (!(!vcyl_retracted && (total_hcyl_pos == 16)) U (wp[15])) || ([] !(!vcyl_retracted && (total_hcyl_pos == 16))) ) }
ltl spurious16_MUST_BE_TRUE { X( (!(!vcyl_retracted && (total_hcyl_pos == 17)) U (wp[16])) || ([] !(!vcyl_retracted && (total_hcyl_pos == 17))) ) }
ltl spurious17_MUST_BE_TRUE { X( (!(!vcyl_retracted && (total_hcyl_pos == 18)) U (wp[17])) || ([] !(!vcyl_retracted && (total_hcyl_pos == 18))) ) }
ltl spurious18_MUST_BE_TRUE { X( (!(!vcyl_retracted && (total_hcyl_pos == 19)) U (wp[18])) || ([] !(!vcyl_retracted && (total_hcyl_pos == 19))) ) }
ltl spurious19_MUST_BE_TRUE { X( (!(!vcyl_retracted && (total_hcyl_pos == 20)) U (wp[19])) || ([] !(!vcyl_retracted && (total_hcyl_pos == 20))) ) }
ltl spurious20_MUST_BE_TRUE { X( (!(!vcyl_retracted && (total_hcyl_pos == 21)) U (wp[20])) || ([] !(!vcyl_retracted && (total_hcyl_pos == 21))) ) }
ltl spurious21_MUST_BE_TRUE { X( (!(!vcyl_retracted && (total_hcyl_pos == 22)) U (wp[21])) || ([] !(!vcyl_retracted && (total_hcyl_pos == 22))) ) }
ltl spurious22_MUST_BE_TRUE { X( (!(!vcyl_retracted && (total_hcyl_pos == 23)) U (wp[22])) || ([] !(!vcyl_retracted && (total_hcyl_pos == 23))) ) }
ltl spurious23_MUST_BE_TRUE { X( (!(!vcyl_retracted && (total_hcyl_pos == 24)) U (wp[23])) || ([] !(!vcyl_retracted && (total_hcyl_pos == 24))) ) }
ltl spurious24_MUST_BE_TRUE { X( (!(!vcyl_retracted && (total_hcyl_pos == 25)) U (wp[24])) || ([] !(!vcyl_retracted && (total_hcyl_pos == 25))) ) }
ltl spurious25_MUST_BE_TRUE { X( (!(!vcyl_retracted && (total_hcyl_pos == 26)) U (wp[25])) || ([] !(!vcyl_retracted && (total_hcyl_pos == 26))) ) }
ltl spurious26_MUST_BE_TRUE { X( (!(!vcyl_retracted && (total_hcyl_pos == 27)) U (wp[26])) || ([] !(!vcyl_retracted && (total_hcyl_pos == 27))) ) }
ltl spurious27_MUST_BE_TRUE { X( (!(!vcyl_retracted && (total_hcyl_pos == 28)) U (wp[27])) || ([] !(!vcyl_retracted && (total_hcyl_pos == 28))) ) }
ltl spurious28_MUST_BE_TRUE { X( (!(!vcyl_retracted && (total_hcyl_pos == 29)) U (wp[28])) || ([] !(!vcyl_retracted && (total_hcyl_pos == 29))) ) }
ltl spurious29_MUST_BE_TRUE { X( (!(!vcyl_retracted && (total_hcyl_pos == 30)) U (wp[29])) || ([] !(!vcyl_retracted && (total_hcyl_pos == 30))) ) }
ltl spurious30_MUST_BE_TRUE { X( (!(!vcyl_retracted && (total_hcyl_pos == 31)) U (wp[30])) || ([] !(!vcyl_retracted && (total_hcyl_pos == 31))) ) }

ltl additional0_MUST_BE_TRUE { X( [](carrying_wp -> <>(wp_output && !suction_on)) ) }
ltl additional1_MUST_BE_TRUE { X( [](suction_on -> (carrying_wp || wp[0] || wp[1] || wp[2] || wp[3] || wp[4] || wp[5] || wp[6] || wp[7] || wp[8] || wp[9] || wp[10] || wp[11] || wp[12] || wp[13] || wp[14] || wp[15] || wp[16] || wp[17] || wp[18] || wp[19] || wp[20] || wp[21] || wp[22] || wp[23] || wp[24] || wp[25] || wp[26] || wp[27] || wp[28] || wp[29] || wp[30])) ) }
ltl additional2_MUST_BE_TRUE { X( [](suction_on -> <> !suction_on) ) }
ltl additional3_MUST_BE_TRUE { X( (!(vcyl_extend || vcyl_extended || suction_on) U (wp[0] || wp[1] || wp[2] || wp[3] || wp[4] || wp[5] || wp[6] || wp[7] || wp[8] || wp[9] || wp[10] || wp[11] || wp[12] || wp[13] || wp[14] || wp[15] || wp[16] || wp[17] || wp[18] || wp[19] || wp[20] || wp[21] || wp[22] || wp[23] || wp[24] || wp[25] || wp[26] || wp[27] || wp[28] || wp[29] || wp[30])) || ([] !(vcyl_extend || vcyl_extended || suction_on)) ) }

ltl order0_MUST_BE_FALSE { X( [](wp[0] -> <>(vcyl_extended && suction_on && carrying_wp && <>(wp_output && vcyl_extended && hcyl_retracted[0] && hcyl_retracted[1] && hcyl_retracted[2] && hcyl_retracted[3] && hcyl_retracted[4] && <>(vcyl_retracted && (hcyl_extended[0] || hcyl_extended[1] || hcyl_extended[2] || hcyl_extended[3] || hcyl_extended[4]))))) ) }
ltl order1_MUST_BE_FALSE { X( [](wp[1] -> <>(vcyl_extended && suction_on && carrying_wp && <>(wp_output && vcyl_extended && hcyl_retracted[0] && hcyl_retracted[1] && hcyl_retracted[2] && hcyl_retracted[3] && hcyl_retracted[4] && <>(vcyl_retracted && (hcyl_extended[0] || hcyl_extended[1] || hcyl_extended[2] || hcyl_extended[3] || hcyl_extended[4]))))) ) }
ltl order2_MUST_BE_FALSE { X( [](wp[2] -> <>(vcyl_extended && suction_on && carrying_wp && <>(wp_output && vcyl_extended && hcyl_retracted[0] && hcyl_retracted[1] && hcyl_retracted[2] && hcyl_retracted[3] && hcyl_retracted[4] && <>(vcyl_retracted && (hcyl_extended[0] || hcyl_extended[1] || hcyl_extended[2] || hcyl_extended[3] || hcyl_extended[4]))))) ) }
ltl order3_MUST_BE_FALSE { X( [](wp[3] -> <>(vcyl_extended && suction_on && carrying_wp && <>(wp_output && vcyl_extended && hcyl_retracted[0] && hcyl_retracted[1] && hcyl_retracted[2] && hcyl_retracted[3] && hcyl_retracted[4] && <>(vcyl_retracted && (hcyl_extended[0] || hcyl_extended[1] || hcyl_extended[2] || hcyl_extended[3] || hcyl_extended[4]))))) ) }
ltl order4_MUST_BE_FALSE { X( [](wp[4] -> <>(vcyl_extended && suction_on && carrying_wp && <>(wp_output && vcyl_extended && hcyl_retracted[0] && hcyl_retracted[1] && hcyl_retracted[2] && hcyl_retracted[3] && hcyl_retracted[4] && <>(vcyl_retracted && (hcyl_extended[0] || hcyl_extended[1] || hcyl_extended[2] || hcyl_extended[3] || hcyl_extended[4]))))) ) }
ltl order5_MUST_BE_FALSE { X( [](wp[5] -> <>(vcyl_extended && suction_on && carrying_wp && <>(wp_output && vcyl_extended && hcyl_retracted[0] && hcyl_retracted[1] && hcyl_retracted[2] && hcyl_retracted[3] && hcyl_retracted[4] && <>(vcyl_retracted && (hcyl_extended[0] || hcyl_extended[1] || hcyl_extended[2] || hcyl_extended[3] || hcyl_extended[4]))))) ) }
ltl order6_MUST_BE_FALSE { X( [](wp[6] -> <>(vcyl_extended && suction_on && carrying_wp && <>(wp_output && vcyl_extended && hcyl_retracted[0] && hcyl_retracted[1] && hcyl_retracted[2] && hcyl_retracted[3] && hcyl_retracted[4] && <>(vcyl_retracted && (hcyl_extended[0] || hcyl_extended[1] || hcyl_extended[2] || hcyl_extended[3] || hcyl_extended[4]))))) ) }
ltl order7_MUST_BE_FALSE { X( [](wp[7] -> <>(vcyl_extended && suction_on && carrying_wp && <>(wp_output && vcyl_extended && hcyl_retracted[0] && hcyl_retracted[1] && hcyl_retracted[2] && hcyl_retracted[3] && hcyl_retracted[4] && <>(vcyl_retracted && (hcyl_extended[0] || hcyl_extended[1] || hcyl_extended[2] || hcyl_extended[3] || hcyl_extended[4]))))) ) }
ltl order8_MUST_BE_FALSE { X( [](wp[8] -> <>(vcyl_extended && suction_on && carrying_wp && <>(wp_output && vcyl_extended && hcyl_retracted[0] && hcyl_retracted[1] && hcyl_retracted[2] && hcyl_retracted[3] && hcyl_retracted[4] && <>(vcyl_retracted && (hcyl_extended[0] || hcyl_extended[1] || hcyl_extended[2] || hcyl_extended[3] || hcyl_extended[4]))))) ) }
ltl order9_MUST_BE_FALSE { X( [](wp[9] -> <>(vcyl_extended && suction_on && carrying_wp && <>(wp_output && vcyl_extended && hcyl_retracted[0] && hcyl_retracted[1] && hcyl_retracted[2] && hcyl_retracted[3] && hcyl_retracted[4] && <>(vcyl_retracted && (hcyl_extended[0] || hcyl_extended[1] || hcyl_extended[2] || hcyl_extended[3] || hcyl_extended[4]))))) ) }
ltl order10_MUST_BE_FALSE { X( [](wp[10] -> <>(vcyl_extended && suction_on && carrying_wp && <>(wp_output && vcyl_extended && hcyl_retracted[0] && hcyl_retracted[1] && hcyl_retracted[2] && hcyl_retracted[3] && hcyl_retracted[4] && <>(vcyl_retracted && (hcyl_extended[0] || hcyl_extended[1] || hcyl_extended[2] || hcyl_extended[3] || hcyl_extended[4]))))) ) }
ltl order11_MUST_BE_FALSE { X( [](wp[11] -> <>(vcyl_extended && suction_on && carrying_wp && <>(wp_output && vcyl_extended && hcyl_retracted[0] && hcyl_retracted[1] && hcyl_retracted[2] && hcyl_retracted[3] && hcyl_retracted[4] && <>(vcyl_retracted && (hcyl_extended[0] || hcyl_extended[1] || hcyl_extended[2] || hcyl_extended[3] || hcyl_extended[4]))))) ) }
ltl order12_MUST_BE_FALSE { X( [](wp[12] -> <>(vcyl_extended && suction_on && carrying_wp && <>(wp_output && vcyl_extended && hcyl_retracted[0] && hcyl_retracted[1] && hcyl_retracted[2] && hcyl_retracted[3] && hcyl_retracted[4] && <>(vcyl_retracted && (hcyl_extended[0] || hcyl_extended[1] || hcyl_extended[2] || hcyl_extended[3] || hcyl_extended[4]))))) ) }
ltl order13_MUST_BE_FALSE { X( [](wp[13] -> <>(vcyl_extended && suction_on && carrying_wp && <>(wp_output && vcyl_extended && hcyl_retracted[0] && hcyl_retracted[1] && hcyl_retracted[2] && hcyl_retracted[3] && hcyl_retracted[4] && <>(vcyl_retracted && (hcyl_extended[0] || hcyl_extended[1] || hcyl_extended[2] || hcyl_extended[3] || hcyl_extended[4]))))) ) }
ltl order14_MUST_BE_FALSE { X( [](wp[14] -> <>(vcyl_extended && suction_on && carrying_wp && <>(wp_output && vcyl_extended && hcyl_retracted[0] && hcyl_retracted[1] && hcyl_retracted[2] && hcyl_retracted[3] && hcyl_retracted[4] && <>(vcyl_retracted && (hcyl_extended[0] || hcyl_extended[1] || hcyl_extended[2] || hcyl_extended[3] || hcyl_extended[4]))))) ) }
ltl order15_MUST_BE_FALSE { X( [](wp[15] -> <>(vcyl_extended && suction_on && carrying_wp && <>(wp_output && vcyl_extended && hcyl_retracted[0] && hcyl_retracted[1] && hcyl_retracted[2] && hcyl_retracted[3] && hcyl_retracted[4] && <>(vcyl_retracted && (hcyl_extended[0] || hcyl_extended[1] || hcyl_extended[2] || hcyl_extended[3] || hcyl_extended[4]))))) ) }
ltl order16_MUST_BE_FALSE { X( [](wp[16] -> <>(vcyl_extended && suction_on && carrying_wp && <>(wp_output && vcyl_extended && hcyl_retracted[0] && hcyl_retracted[1] && hcyl_retracted[2] && hcyl_retracted[3] && hcyl_retracted[4] && <>(vcyl_retracted && (hcyl_extended[0] || hcyl_extended[1] || hcyl_extended[2] || hcyl_extended[3] || hcyl_extended[4]))))) ) }
ltl order17_MUST_BE_FALSE { X( [](wp[17] -> <>(vcyl_extended && suction_on && carrying_wp && <>(wp_output && vcyl_extended && hcyl_retracted[0] && hcyl_retracted[1] && hcyl_retracted[2] && hcyl_retracted[3] && hcyl_retracted[4] && <>(vcyl_retracted && (hcyl_extended[0] || hcyl_extended[1] || hcyl_extended[2] || hcyl_extended[3] || hcyl_extended[4]))))) ) }
ltl order18_MUST_BE_FALSE { X( [](wp[18] -> <>(vcyl_extended && suction_on && carrying_wp && <>(wp_output && vcyl_extended && hcyl_retracted[0] && hcyl_retracted[1] && hcyl_retracted[2] && hcyl_retracted[3] && hcyl_retracted[4] && <>(vcyl_retracted && (hcyl_extended[0] || hcyl_extended[1] || hcyl_extended[2] || hcyl_extended[3] || hcyl_extended[4]))))) ) }
ltl order19_MUST_BE_FALSE { X( [](wp[19] -> <>(vcyl_extended && suction_on && carrying_wp && <>(wp_output && vcyl_extended && hcyl_retracted[0] && hcyl_retracted[1] && hcyl_retracted[2] && hcyl_retracted[3] && hcyl_retracted[4] && <>(vcyl_retracted && (hcyl_extended[0] || hcyl_extended[1] || hcyl_extended[2] || hcyl_extended[3] || hcyl_extended[4]))))) ) }
ltl order20_MUST_BE_FALSE { X( [](wp[20] -> <>(vcyl_extended && suction_on && carrying_wp && <>(wp_output && vcyl_extended && hcyl_retracted[0] && hcyl_retracted[1] && hcyl_retracted[2] && hcyl_retracted[3] && hcyl_retracted[4] && <>(vcyl_retracted && (hcyl_extended[0] || hcyl_extended[1] || hcyl_extended[2] || hcyl_extended[3] || hcyl_extended[4]))))) ) }
ltl order21_MUST_BE_FALSE { X( [](wp[21] -> <>(vcyl_extended && suction_on && carrying_wp && <>(wp_output && vcyl_extended && hcyl_retracted[0] && hcyl_retracted[1] && hcyl_retracted[2] && hcyl_retracted[3] && hcyl_retracted[4] && <>(vcyl_retracted && (hcyl_extended[0] || hcyl_extended[1] || hcyl_extended[2] || hcyl_extended[3] || hcyl_extended[4]))))) ) }
ltl order22_MUST_BE_FALSE { X( [](wp[22] -> <>(vcyl_extended && suction_on && carrying_wp && <>(wp_output && vcyl_extended && hcyl_retracted[0] && hcyl_retracted[1] && hcyl_retracted[2] && hcyl_retracted[3] && hcyl_retracted[4] && <>(vcyl_retracted && (hcyl_extended[0] || hcyl_extended[1] || hcyl_extended[2] || hcyl_extended[3] || hcyl_extended[4]))))) ) }
ltl order23_MUST_BE_FALSE { X( [](wp[23] -> <>(vcyl_extended && suction_on && carrying_wp && <>(wp_output && vcyl_extended && hcyl_retracted[0] && hcyl_retracted[1] && hcyl_retracted[2] && hcyl_retracted[3] && hcyl_retracted[4] && <>(vcyl_retracted && (hcyl_extended[0] || hcyl_extended[1] || hcyl_extended[2] || hcyl_extended[3] || hcyl_extended[4]))))) ) }
ltl order24_MUST_BE_FALSE { X( [](wp[24] -> <>(vcyl_extended && suction_on && carrying_wp && <>(wp_output && vcyl_extended && hcyl_retracted[0] && hcyl_retracted[1] && hcyl_retracted[2] && hcyl_retracted[3] && hcyl_retracted[4] && <>(vcyl_retracted && (hcyl_extended[0] || hcyl_extended[1] || hcyl_extended[2] || hcyl_extended[3] || hcyl_extended[4]))))) ) }
ltl order25_MUST_BE_FALSE { X( [](wp[25] -> <>(vcyl_extended && suction_on && carrying_wp && <>(wp_output && vcyl_extended && hcyl_retracted[0] && hcyl_retracted[1] && hcyl_retracted[2] && hcyl_retracted[3] && hcyl_retracted[4] && <>(vcyl_retracted && (hcyl_extended[0] || hcyl_extended[1] || hcyl_extended[2] || hcyl_extended[3] || hcyl_extended[4]))))) ) }
ltl order26_MUST_BE_FALSE { X( [](wp[26] -> <>(vcyl_extended && suction_on && carrying_wp && <>(wp_output && vcyl_extended && hcyl_retracted[0] && hcyl_retracted[1] && hcyl_retracted[2] && hcyl_retracted[3] && hcyl_retracted[4] && <>(vcyl_retracted && (hcyl_extended[0] || hcyl_extended[1] || hcyl_extended[2] || hcyl_extended[3] || hcyl_extended[4]))))) ) }
ltl order27_MUST_BE_FALSE { X( [](wp[27] -> <>(vcyl_extended && suction_on && carrying_wp && <>(wp_output && vcyl_extended && hcyl_retracted[0] && hcyl_retracted[1] && hcyl_retracted[2] && hcyl_retracted[3] && hcyl_retracted[4] && <>(vcyl_retracted && (hcyl_extended[0] || hcyl_extended[1] || hcyl_extended[2] || hcyl_extended[3] || hcyl_extended[4]))))) ) }
ltl order28_MUST_BE_FALSE { X( [](wp[28] -> <>(vcyl_extended && suction_on && carrying_wp && <>(wp_output && vcyl_extended && hcyl_retracted[0] && hcyl_retracted[1] && hcyl_retracted[2] && hcyl_retracted[3] && hcyl_retracted[4] && <>(vcyl_retracted && (hcyl_extended[0] || hcyl_extended[1] || hcyl_extended[2] || hcyl_extended[3] || hcyl_extended[4]))))) ) }
ltl order29_MUST_BE_FALSE { X( [](wp[29] -> <>(vcyl_extended && suction_on && carrying_wp && <>(wp_output && vcyl_extended && hcyl_retracted[0] && hcyl_retracted[1] && hcyl_retracted[2] && hcyl_retracted[3] && hcyl_retracted[4] && <>(vcyl_retracted && (hcyl_extended[0] || hcyl_extended[1] || hcyl_extended[2] || hcyl_extended[3] || hcyl_extended[4]))))) ) }
ltl order30_MUST_BE_FALSE { X( [](wp[30] -> <>(vcyl_extended && suction_on && carrying_wp && <>(wp_output && vcyl_extended && hcyl_retracted[0] && hcyl_retracted[1] && hcyl_retracted[2] && hcyl_retracted[3] && hcyl_retracted[4] && <>(vcyl_retracted && (hcyl_extended[0] || hcyl_extended[1] || hcyl_extended[2] || hcyl_extended[3] || hcyl_extended[4]))))) ) }

ltl disappear0_MUST_BE_FALSE { X( []((wp[0] && !adding_wp[0]) -> <> !wp[0]) ) }
ltl disappear1_MUST_BE_FALSE { X( []((wp[1] && !adding_wp[1]) -> <> !wp[1]) ) }
ltl disappear2_MUST_BE_FALSE { X( []((wp[2] && !adding_wp[2]) -> <> !wp[2]) ) }
ltl disappear3_MUST_BE_FALSE { X( []((wp[3] && !adding_wp[3]) -> <> !wp[3]) ) }
ltl disappear4_MUST_BE_FALSE { X( []((wp[4] && !adding_wp[4]) -> <> !wp[4]) ) }
ltl disappear5_MUST_BE_FALSE { X( []((wp[5] && !adding_wp[5]) -> <> !wp[5]) ) }
ltl disappear6_MUST_BE_FALSE { X( []((wp[6] && !adding_wp[6]) -> <> !wp[6]) ) }
ltl disappear7_MUST_BE_FALSE { X( []((wp[7] && !adding_wp[7]) -> <> !wp[7]) ) }
ltl disappear8_MUST_BE_FALSE { X( []((wp[8] && !adding_wp[8]) -> <> !wp[8]) ) }
ltl disappear9_MUST_BE_FALSE { X( []((wp[9] && !adding_wp[9]) -> <> !wp[9]) ) }
ltl disappear10_MUST_BE_FALSE { X( []((wp[10] && !adding_wp[10]) -> <> !wp[10]) ) }
ltl disappear11_MUST_BE_FALSE { X( []((wp[11] && !adding_wp[11]) -> <> !wp[11]) ) }
ltl disappear12_MUST_BE_FALSE { X( []((wp[12] && !adding_wp[12]) -> <> !wp[12]) ) }
ltl disappear13_MUST_BE_FALSE { X( []((wp[13] && !adding_wp[13]) -> <> !wp[13]) ) }
ltl disappear14_MUST_BE_FALSE { X( []((wp[14] && !adding_wp[14]) -> <> !wp[14]) ) }
ltl disappear15_MUST_BE_FALSE { X( []((wp[15] && !adding_wp[15]) -> <> !wp[15]) ) }
ltl disappear16_MUST_BE_FALSE { X( []((wp[16] && !adding_wp[16]) -> <> !wp[16]) ) }
ltl disappear17_MUST_BE_FALSE { X( []((wp[17] && !adding_wp[17]) -> <> !wp[17]) ) }
ltl disappear18_MUST_BE_FALSE { X( []((wp[18] && !adding_wp[18]) -> <> !wp[18]) ) }
ltl disappear19_MUST_BE_FALSE { X( []((wp[19] && !adding_wp[19]) -> <> !wp[19]) ) }
ltl disappear20_MUST_BE_FALSE { X( []((wp[20] && !adding_wp[20]) -> <> !wp[20]) ) }
ltl disappear21_MUST_BE_FALSE { X( []((wp[21] && !adding_wp[21]) -> <> !wp[21]) ) }
ltl disappear22_MUST_BE_FALSE { X( []((wp[22] && !adding_wp[22]) -> <> !wp[22]) ) }
ltl disappear23_MUST_BE_FALSE { X( []((wp[23] && !adding_wp[23]) -> <> !wp[23]) ) }
ltl disappear24_MUST_BE_FALSE { X( []((wp[24] && !adding_wp[24]) -> <> !wp[24]) ) }
ltl disappear25_MUST_BE_FALSE { X( []((wp[25] && !adding_wp[25]) -> <> !wp[25]) ) }
ltl disappear26_MUST_BE_FALSE { X( []((wp[26] && !adding_wp[26]) -> <> !wp[26]) ) }
ltl disappear27_MUST_BE_FALSE { X( []((wp[27] && !adding_wp[27]) -> <> !wp[27]) ) }
ltl disappear28_MUST_BE_FALSE { X( []((wp[28] && !adding_wp[28]) -> <> !wp[28]) ) }
ltl disappear29_MUST_BE_FALSE { X( []((wp[29] && !adding_wp[29]) -> <> !wp[29]) ) }
ltl disappear30_MUST_BE_FALSE { X( []((wp[30] && !adding_wp[30]) -> <> !wp[30]) ) }

ltl spurious0_MUST_BE_FALSE { X( (!(total_hcyl_pos == 1) U (wp[0])) || ([] !(total_hcyl_pos == 1)) ) }
ltl spurious1_MUST_BE_FALSE { X( (!(total_hcyl_pos == 2) U (wp[1])) || ([] !(total_hcyl_pos == 2)) ) }
ltl spurious2_MUST_BE_FALSE { X( (!(total_hcyl_pos == 3) U (wp[2])) || ([] !(total_hcyl_pos == 3)) ) }
ltl spurious3_MUST_BE_FALSE { X( (!(total_hcyl_pos == 4) U (wp[3])) || ([] !(total_hcyl_pos == 4)) ) }
ltl spurious4_MUST_BE_FALSE { X( (!(total_hcyl_pos == 5) U (wp[4])) || ([] !(total_hcyl_pos == 5)) ) }
ltl spurious5_MUST_BE_FALSE { X( (!(total_hcyl_pos == 6) U (wp[5])) || ([] !(total_hcyl_pos == 6)) ) }
ltl spurious6_MUST_BE_FALSE { X( (!(total_hcyl_pos == 7) U (wp[6])) || ([] !(total_hcyl_pos == 7)) ) }
ltl spurious7_MUST_BE_FALSE { X( (!(total_hcyl_pos == 8) U (wp[7])) || ([] !(total_hcyl_pos == 8)) ) }
ltl spurious8_MUST_BE_FALSE { X( (!(total_hcyl_pos == 9) U (wp[8])) || ([] !(total_hcyl_pos == 9)) ) }
ltl spurious9_MUST_BE_FALSE { X( (!(total_hcyl_pos == 10) U (wp[9])) || ([] !(total_hcyl_pos == 10)) ) }
ltl spurious10_MUST_BE_FALSE { X( (!(total_hcyl_pos == 11) U (wp[10])) || ([] !(total_hcyl_pos == 11)) ) }
ltl spurious11_MUST_BE_FALSE { X( (!(total_hcyl_pos == 12) U (wp[11])) || ([] !(total_hcyl_pos == 12)) ) }
ltl spurious12_MUST_BE_FALSE { X( (!(total_hcyl_pos == 13) U (wp[12])) || ([] !(total_hcyl_pos == 13)) ) }
ltl spurious13_MUST_BE_FALSE { X( (!(total_hcyl_pos == 14) U (wp[13])) || ([] !(total_hcyl_pos == 14)) ) }
ltl spurious14_MUST_BE_FALSE { X( (!(total_hcyl_pos == 15) U (wp[14])) || ([] !(total_hcyl_pos == 15)) ) }
ltl spurious15_MUST_BE_FALSE { X( (!(total_hcyl_pos == 16) U (wp[15])) || ([] !(total_hcyl_pos == 16)) ) }
ltl spurious16_MUST_BE_FALSE { X( (!(total_hcyl_pos == 17) U (wp[16])) || ([] !(total_hcyl_pos == 17)) ) }
ltl spurious17_MUST_BE_FALSE { X( (!(total_hcyl_pos == 18) U (wp[17])) || ([] !(total_hcyl_pos == 18)) ) }
ltl spurious18_MUST_BE_FALSE { X( (!(total_hcyl_pos == 19) U (wp[18])) || ([] !(total_hcyl_pos == 19)) ) }
ltl spurious19_MUST_BE_FALSE { X( (!(total_hcyl_pos == 20) U (wp[19])) || ([] !(total_hcyl_pos == 20)) ) }
ltl spurious20_MUST_BE_FALSE { X( (!(total_hcyl_pos == 21) U (wp[20])) || ([] !(total_hcyl_pos == 21)) ) }
ltl spurious21_MUST_BE_FALSE { X( (!(total_hcyl_pos == 22) U (wp[21])) || ([] !(total_hcyl_pos == 22)) ) }
ltl spurious22_MUST_BE_FALSE { X( (!(total_hcyl_pos == 23) U (wp[22])) || ([] !(total_hcyl_pos == 23)) ) }
ltl spurious23_MUST_BE_FALSE { X( (!(total_hcyl_pos == 24) U (wp[23])) || ([] !(total_hcyl_pos == 24)) ) }
ltl spurious24_MUST_BE_FALSE { X( (!(total_hcyl_pos == 25) U (wp[24])) || ([] !(total_hcyl_pos == 25)) ) }
ltl spurious25_MUST_BE_FALSE { X( (!(total_hcyl_pos == 26) U (wp[25])) || ([] !(total_hcyl_pos == 26)) ) }
ltl spurious26_MUST_BE_FALSE { X( (!(total_hcyl_pos == 27) U (wp[26])) || ([] !(total_hcyl_pos == 27)) ) }
ltl spurious27_MUST_BE_FALSE { X( (!(total_hcyl_pos == 28) U (wp[27])) || ([] !(total_hcyl_pos == 28)) ) }
ltl spurious28_MUST_BE_FALSE { X( (!(total_hcyl_pos == 29) U (wp[28])) || ([] !(total_hcyl_pos == 29)) ) }
ltl spurious29_MUST_BE_FALSE { X( (!(total_hcyl_pos == 30) U (wp[29])) || ([] !(total_hcyl_pos == 30)) ) }

ltl additional0_MUST_BE_FALSE { X( [](carrying_wp -> suction_on) ) }
ltl additional1_MUST_BE_FALSE { X( [](suction_on -> (wp[0] || wp[1] || wp[2] || wp[3] || wp[4] || wp[5] || wp[6] || wp[7] || wp[8] || wp[9] || wp[10] || wp[11] || wp[12] || wp[13] || wp[14] || wp[15] || wp[16] || wp[17] || wp[18] || wp[19] || wp[20] || wp[21] || wp[22] || wp[23] || wp[24] || wp[25] || wp[26] || wp[27] || wp[28] || wp[29] || wp[30])) ) }
ltl additional2_MUST_BE_FALSE { X( [](suction_on -> carrying_wp) ) }
ltl additional3_MUST_BE_FALSE { X( (!(vcyl_extend || vcyl_extended || suction_on) U (wp[0] && wp[1] && wp[2] && wp[3] && wp[4] && wp[5] && wp[6] && wp[7] && wp[8] && wp[9] && wp[10] && wp[11] && wp[12] && wp[13] && wp[14] && wp[15] && wp[16] && wp[17] && wp[18] && wp[19] && wp[20] && wp[21] && wp[22] && wp[23] && wp[24] && wp[25] && wp[26] && wp[27] && wp[28] && wp[29] && wp[30])) || ([] !(vcyl_extend || vcyl_extended || suction_on)) ) }
